//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh__Config__PTofCls__LMCPublisher 
  {
    CHMETH *pMeth;
    _Config_ dData;
    SVRDSC *pDsc;
  } SvrCh__Config__PTofCls__LMCPublisher;

typedef struct CltCh__Config__PTofCls__LMCPublisher 
  {
    struct SvrCh__Config__PTofCls__LMCPublisher *pCh;
    _Config_ dData;
    SVRCHCMD *pCmd;
  } CltCh__Config__PTofCls__LMCPublisher;

typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct CltCh_BDINT 
  {
    struct SvrCh_BDINT *pCh;
    BDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_BDINT;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_FeSetup 
  {
    CHMETH *pMeth;
    FeSetup dData;
    SVRDSC *pDsc;
  } SvrCh_FeSetup;

typedef struct CltCh_FeSetup 
  {
    struct SvrCh_FeSetup *pCh;
    FeSetup dData;
    SVRCHCMD *pCmd;
  } CltCh_FeSetup;

typedef struct SvrCh_IO_State 
  {
    CHMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrCh_IO_State;

typedef struct CltCh_IO_State 
  {
    struct SvrCh_IO_State *pCh;
    IO_State dData;
    SVRCHCMD *pCmd;
  } CltCh_IO_State;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd__LMCAXIS_OPMODE 
  {
    CMDMETH *pMeth;
    _LMCAXIS_OPMODE dData;
    SVRDSC *pDsc;
  } SvrChCmd__LMCAXIS_OPMODE;

typedef struct CltChCmd__AxisBase 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _AxisBase *pCmd;
  } CltChCmd__AxisBase;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__CanLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CanLib *pCmd;
  } CltChCmd__CanLib;

typedef struct CltChCmd__CheckSum 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CheckSum *pCmd;
  } CltChCmd__CheckSum;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Linker 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Linker *pCmd;
  } CltChCmd__Linker;

typedef struct CltChCmd__LMCABSEncoder 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCABSEncoder *pCmd;
  } CltChCmd__LMCABSEncoder;

typedef struct CltChCmd__LMCAxis 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxis *pCmd;
  } CltChCmd__LMCAxis;

typedef struct CltChCmd__LMCAxisBase 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxisBase *pCmd;
  } CltChCmd__LMCAxisBase;

typedef struct CltChCmd__LMCAxisRef 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisRef *pCmd;
  } CltChCmd__LMCAxisRef;

typedef struct CltChCmd__LMCAxisVis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVis *pCmd;
  } CltChCmd__LMCAxisVis;

typedef struct CltChCmd__LMCAxisVisInt 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisInt *pCmd;
  } CltChCmd__LMCAxisVisInt;

typedef struct CltChCmd__LMCAxisVisLogHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogHandle *pCmd;
  } CltChCmd__LMCAxisVisLogHandle;

typedef struct CltChCmd__LMCAxisVisLogViewer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogViewer *pCmd;
  } CltChCmd__LMCAxisVisLogViewer;

typedef struct CltChCmd__LMCAxisVisPara 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisPara *pCmd;
  } CltChCmd__LMCAxisVisPara;

typedef struct CltChCmd__LMCAxisVOVMonitoring 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVOVMonitoring *pCmd;
  } CltChCmd__LMCAxisVOVMonitoring;

typedef struct CltChCmd__LMCBaseCoord 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCBaseCoord *pCmd;
  } CltChCmd__LMCBaseCoord;

typedef struct CltChCmd__LMCBeltAxis 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCBeltAxis *pCmd;
  } CltChCmd__LMCBeltAxis;

typedef struct SvrChCmd_ProfileCommandStatus 
  {
    CMDMETH *pMeth;
    ProfileCommandStatus dData;
    SVRDSC *pDsc;
  } SvrChCmd_ProfileCommandStatus;

typedef struct CltChCmd__LMCCalcModelBase 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    _LMCCalcModelBase *pCmd;
  } CltChCmd__LMCCalcModelBase;

typedef struct CltChCmd__LMCCalcModelController 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCCalcModelController *pCmd;
  } CltChCmd__LMCCalcModelController;

typedef struct CltChCmd__LMCMath_SO3 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCMath_SO3 *pCmd;
  } CltChCmd__LMCMath_SO3;

typedef struct CltChCmd__LMCMathFunctions 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCMathFunctions *pCmd;
  } CltChCmd__LMCMathFunctions;

typedef struct CltChCmd__LMCProfileBase 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    _LMCProfileBase *pCmd;
  } CltChCmd__LMCProfileBase;

typedef struct CltChCmd__LMCProfileBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileBuffer *pCmd;
  } CltChCmd__LMCProfileBuffer;

typedef struct CltChCmd__LMCProfileLog 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileLog *pCmd;
  } CltChCmd__LMCProfileLog;

typedef struct CltChCmd__LMCProfileVis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVis *pCmd;
  } CltChCmd__LMCProfileVis;

typedef struct CltChCmd__LMCProfileVisAxis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisAxis *pCmd;
  } CltChCmd__LMCProfileVisAxis;

typedef struct CltChCmd__LMCProfileVisInt 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisInt *pCmd;
  } CltChCmd__LMCProfileVisInt;

typedef struct CltChCmd__LMCProfileVisMovePara 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCProfileVisMovePara *pCmd;
  } CltChCmd__LMCProfileVisMovePara;

typedef struct CltChCmd__LMCPublisher 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCPublisher *pCmd;
  } CltChCmd__LMCPublisher;

typedef struct CltChCmd__LMCRefBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCRefBase *pCmd;
  } CltChCmd__LMCRefBase;

typedef struct CltChCmd__LMCRobotBase 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    _LMCRobotBase *pCmd;
  } CltChCmd__LMCRobotBase;

typedef struct CltChCmd__LMCRobotLog 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCRobotLog *pCmd;
  } CltChCmd__LMCRobotLog;

typedef struct CltChCmd__LMCSafety 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCSafety *pCmd;
  } CltChCmd__LMCSafety;

typedef struct CltChCmd__LMCSplineBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCSplineBuffer *pCmd;
  } CltChCmd__LMCSplineBuffer;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd__LMCTableBuffer 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    _LMCTableBuffer *pCmd;
  } CltChCmd__LMCTableBuffer;

typedef struct CltChCmd__LMCTool 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCTool *pCmd;
  } CltChCmd__LMCTool;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__SerLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SerLib *pCmd;
  } CltChCmd__SerLib;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct CltChCmd__SyncMeasureECAT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SyncMeasureECAT *pCmd;
  } CltChCmd__SyncMeasureECAT;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct SvrChCmd__FSM_TCPIP_SERVER_PTofCls__TCPIPServer 
  {
    CMDMETH *pMeth;
    _FSM_TCPIP_SERVER dData;
    SVRDSC *pDsc;
  } SvrChCmd__FSM_TCPIP_SERVER_PTofCls__TCPIPServer;

typedef struct CltChCmd__TCPIPServer 
  {
    struct SvrChCmd__FSM_TCPIP_SERVER_PTofCls__TCPIPServer *pCh;
    _FSM_TCPIP_SERVER dData;
    _TCPIPServer *pCmd;
  } CltChCmd__TCPIPServer;

typedef struct CltChCmd_ASCII_BIN 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ASCII_BIN *pCmd;
  } CltChCmd_ASCII_BIN;

typedef struct CltChCmd_Controller 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Controller *pCmd;
  } CltChCmd_Controller;

typedef struct CltChCmd_CriticalSection 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    CriticalSection *pCmd;
  } CltChCmd_CriticalSection;

typedef struct CltChCmd_DiasMaster 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMaster *pCmd;
  } CltChCmd_DiasMaster;

typedef struct CltChCmd_DiasMasterC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterC *pCmd;
  } CltChCmd_DiasMasterC;

typedef struct CltChCmd_DiasMasterPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterPostScan *pCmd;
  } CltChCmd_DiasMasterPostScan;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct SvrChCmd_t_e_VaranErrors 
  {
    CMDMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrChCmd_t_e_VaranErrors;

typedef struct CltChCmd_ECAT_Master_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    ECAT_Master_Base *pCmd;
  } CltChCmd_ECAT_Master_Base;

typedef struct CltChCmd_ECAT_Slave_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    ECAT_Slave_Base *pCmd;
  } CltChCmd_ECAT_Slave_Base;

typedef struct CltChCmd_EEPROM 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EEPROM *pCmd;
  } CltChCmd_EEPROM;

typedef struct CltChCmd_Elmo_1 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Elmo_1 *pCmd;
  } CltChCmd_Elmo_1;

typedef struct CltChCmd_Elmo_2 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Elmo_2 *pCmd;
  } CltChCmd_Elmo_2;

typedef struct CltChCmd_Elmo_3 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Elmo_3 *pCmd;
  } CltChCmd_Elmo_3;

typedef struct CltChCmd_Elmo_4 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Elmo_4 *pCmd;
  } CltChCmd_Elmo_4;

typedef struct CltChCmd_EtherCAT_Hub_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EtherCAT_Hub_Base *pCmd;
  } CltChCmd_EtherCAT_Hub_Base;

typedef struct CltChCmd_GetCILInterface 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetCILInterface *pCmd;
  } CltChCmd_GetCILInterface;

typedef struct CltChCmd_Hub_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base *pCmd;
  } CltChCmd_Hub_Base;

typedef struct CltChCmd_Hub_Base_Root 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base_Root *pCmd;
  } CltChCmd_Hub_Base_Root;

typedef struct CltChCmd_HwcLogging 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwcLogging *pCmd;
  } CltChCmd_HwcLogging;

typedef struct CltChCmd_HwControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControl *pCmd;
  } CltChCmd_HwControl;

typedef struct CltChCmd_HwControlBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControlBase *pCmd;
  } CltChCmd_HwControlBase;

typedef struct CltChCmd_HWRtPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWRtPostScan *pCmd;
  } CltChCmd_HWRtPostScan;

typedef struct CltChCmd_I2CCDIAS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    I2CCDIAS *pCmd;
  } CltChCmd_I2CCDIAS;

typedef struct CltChCmd_LMCControlCommandService 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    LMCControlCommandService *pCmd;
  } CltChCmd_LMCControlCommandService;

typedef struct CltChCmd_LMCDiagnosticsService 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    LMCDiagnosticsService *pCmd;
  } CltChCmd_LMCDiagnosticsService;

typedef struct CltChCmd_LMCEcatInputLatch 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    LMCEcatInputLatch *pCmd;
  } CltChCmd_LMCEcatInputLatch;

typedef struct CltChCmd_LMCRecorderStore 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    LMCRecorderStore *pCmd;
  } CltChCmd_LMCRecorderStore;

typedef struct SvrChCmd_iprStates 
  {
    CMDMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrChCmd_iprStates;

typedef struct CltChCmd_LMCSdoExecutor 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    LMCSdoExecutor *pCmd;
  } CltChCmd_LMCSdoExecutor;

typedef struct CltChCmd_Merker 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Merker *pCmd;
  } CltChCmd_Merker;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_ProfileCommandStatus 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    SVRCHCMD *pCmd;
  } CltChCmd_ProfileCommandStatus;

typedef struct CltChCmd_RamFile 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamFile *pCmd;
  } CltChCmd_RamFile;

typedef struct CltChCmd_SafetyManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SafetyManager *pCmd;
  } CltChCmd_SafetyManager;

typedef struct CltChCmd_SafetyRoutingTables 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SafetyRoutingTables *pCmd;
  } CltChCmd_SafetyRoutingTables;

typedef struct CltChCmd_SdiasHubBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasHubBase *pCmd;
  } CltChCmd_SdiasHubBase;

typedef struct CltChCmd_SdiasManager 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SdiasManager *pCmd;
  } CltChCmd_SdiasManager;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct SvrChCmd_IO_State 
  {
    CMDMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrChCmd_IO_State;

typedef struct CltChCmd_SyncCall 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    SyncCall *pCmd;
  } CltChCmd_SyncCall;

typedef struct CltChCmd_t_e_VaranErrors 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SVRCHCMD *pCmd;
  } CltChCmd_t_e_VaranErrors;

typedef struct CltChCmd_Varan_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Varan_Base *pCmd;
  } CltChCmd_Varan_Base;

typedef struct CltChCmd_VaranManager_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    VaranManager_Base *pCmd;
  } CltChCmd_VaranManager_Base;

typedef struct CltChCmd_WatchdogDias 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    WatchdogDias *pCmd;
  } CltChCmd_WatchdogDias;

typedef struct CltChCmd_XXXBase_IOs 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    XXXBase_IOs *pCmd;
  } CltChCmd_XXXBase_IOs;

typedef struct SvrCh__CommandList_PTofCls__LMCAxisBase 
  {
    CHMETH *pMeth;
    _CommandList dData;
    SVRDSC *pDsc;
  } SvrCh__CommandList_PTofCls__LMCAxisBase;

typedef struct SvrCh__FSM_TCPIP_SERVER_PTofCls__TCPIPServer 
  {
    CHMETH *pMeth;
    _FSM_TCPIP_SERVER dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_TCPIP_SERVER_PTofCls__TCPIPServer;

typedef struct SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP;

typedef struct SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_USER dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP;

typedef struct SvrCh__INITSTEPS_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _INITSTEPS dData;
    SVRDSC *pDsc;
  } SvrCh__INITSTEPS_PTofCls_SafetyUDP;

typedef struct SvrCh__LMCAXIS_CMDERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_CMDERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_CMDERROR;

typedef struct SvrCh__LMCAXIS_ERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR;

typedef struct SvrCh__LMCAXIS_ERROR_CONFIG 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR_CONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR_CONFIG;

typedef struct SvrCh__LMCAXIS_MOVE_RELATIVE_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVE_RELATIVE_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVE_RELATIVE_MODE;

typedef struct SvrCh__LMCAXIS_MOVEDIRECTION 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEDIRECTION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEDIRECTION;

typedef struct SvrCh__LMCAXIS_MOVEPROFILE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEPROFILE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEPROFILE;

typedef struct SvrCh__LMCAXIS_OPMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_OPMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_OPMODE;

typedef struct SvrCh__LMCAXIS_POSMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POSMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POSMODE;

typedef struct SvrCh__LMCAXIS_POWER_OFF_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POWER_OFF_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POWER_OFF_MODE;

typedef struct SvrCh__LMCAXIS_REFMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_REFMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_REFMODE;

typedef struct SvrCh__LMCAXIS_SETPARAMETER 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPARAMETER dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPARAMETER;

typedef struct SvrCh__LMCAXIS_SETPOSITION 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPOSITION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPOSITION;

typedef struct SvrCh__LMCAXIS_SETSWENDPOS 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETSWENDPOS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETSWENDPOS;

typedef struct SvrCh__LMCAXIS_STATUS 
  {
    CHMETH *pMeth;
    _LMCAXIS_STATUS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_STATUS;

typedef struct SvrCh__LMCCONTROLLERTYPE 
  {
    CHMETH *pMeth;
    _LMCCONTROLLERTYPE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCCONTROLLERTYPE;

typedef struct SvrCh__LMCPROF_OPMODE 
  {
    CHMETH *pMeth;
    _LMCPROF_OPMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROF_OPMODE;

typedef struct SvrCh__LMCPROFCIRCLEDEF 
  {
    CHMETH *pMeth;
    _LMCPROFCIRCLEDEF dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCIRCLEDEF;

typedef struct SvrCh__LMCPROFCMDCONFIG 
  {
    CHMETH *pMeth;
    _LMCPROFCMDCONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCMDCONFIG;

typedef struct SvrCh__LMCPROFCMDTYPES 
  {
    CHMETH *pMeth;
    _LMCPROFCMDTYPES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFCMDTYPES;

typedef struct SvrCh__LMCPROFERRORTYPES 
  {
    CHMETH *pMeth;
    _LMCPROFERRORTYPES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFERRORTYPES;

typedef struct SvrCh__LMCPROFERRWARNCONFIG 
  {
    CHMETH *pMeth;
    _LMCPROFERRWARNCONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFERRWARNCONFIG;

typedef struct SvrCh__LMCPROFILESTATES 
  {
    CHMETH *pMeth;
    _LMCPROFILESTATES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFILESTATES;

typedef struct SvrCh__LMCPROFMOVEPROFILE 
  {
    CHMETH *pMeth;
    _LMCPROFMOVEPROFILE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFMOVEPROFILE;

typedef struct SvrCh__LMCPROFPARAMETER 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETER dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETER;

typedef struct SvrCh__LMCPROFPARAMETERAXIS 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETERAXIS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETERAXIS;

typedef struct SvrCh__LMCPROFPARAMETERGROUPS 
  {
    CHMETH *pMeth;
    _LMCPROFPARAMETERGROUPS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFPARAMETERGROUPS;

typedef struct SvrCh__LMCPROFTRANSMODES 
  {
    CHMETH *pMeth;
    _LMCPROFTRANSMODES dData;
    SVRDSC *pDsc;
  } SvrCh__LMCPROFTRANSMODES;

typedef struct SvrCh__POSFLAGS 
  {
    CHMETH *pMeth;
    _POSFLAGS dData;
    SVRDSC *pDsc;
  } SvrCh__POSFLAGS;

typedef struct SvrCh__ROBOT_MODE_PTofCls__LMCRobotBase 
  {
    CHMETH *pMeth;
    _ROBOT_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__ROBOT_MODE_PTofCls__LMCRobotBase;

typedef struct SvrCh__ROBOT_STATUS_PTofCls__LMCRobotBase 
  {
    CHMETH *pMeth;
    _ROBOT_STATUS dData;
    SVRDSC *pDsc;
  } SvrCh__ROBOT_STATUS_PTofCls__LMCRobotBase;

typedef struct SvrCh__STATE_TCPIP_INTF_PTofCls__TCPIPServerInterface 
  {
    CHMETH *pMeth;
    _STATE_TCPIP_INTF dData;
    SVRDSC *pDsc;
  } SvrCh__STATE_TCPIP_INTF_PTofCls__TCPIPServerInterface;

typedef struct SvrCh_DS402_Control 
  {
    CHMETH *pMeth;
    DS402_Control dData;
    SVRDSC *pDsc;
  } SvrCh_DS402_Control;

typedef struct SvrCh_DS402_State 
  {
    CHMETH *pMeth;
    DS402_State dData;
    SVRDSC *pDsc;
  } SvrCh_DS402_State;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct SvrCh_SafetyConfigStateType 
  {
    CHMETH *pMeth;
    SafetyConfigStateType dData;
    SVRDSC *pDsc;
  } SvrCh_SafetyConfigStateType;

typedef struct SvrCh_t_e_ECAT_STATE 
  {
    CHMETH *pMeth;
    t_e_ECAT_STATE dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_ECAT_STATE;

typedef struct SvrCh_t_e_SafetyMemState 
  {
    CHMETH *pMeth;
    t_e_SafetyMemState dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_SafetyMemState;

typedef struct SvrCh_t_e_VaranErrors 
  {
    CHMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_VaranErrors;

typedef struct SvrCh_t_s_LMCAxis_SafetyState_PTofCls__LMCAxisBase 
  {
    CHMETH *pMeth;
    t_s_LMCAxis_SafetyState dData;
    SVRDSC *pDsc;
  } SvrCh_t_s_LMCAxis_SafetyState_PTofCls__LMCAxisBase;

