//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SvrCh__Config__PTofCls__LMCPublisher : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPublisher::_Config_;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh__Config__PTofCls__LMCPublisher : STRUCT
    pCh : ^SvrCh__Config__PTofCls__LMCPublisher;
    dData : _LMCPublisher::_Config_;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_BDINT : STRUCT
    pMeth : ^CHMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_BDINT : STRUCT
    pCh : ^SvrCh_BDINT;
    dData : BDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_DINT : STRUCT
    pMeth : ^CHMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_DINT : STRUCT
    pCh : ^SvrCh_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_FeSetup : STRUCT
    pMeth : ^CHMETH;
    dData : FeSetup;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_FeSetup : STRUCT
    pCh : ^SvrCh_FeSetup;
    dData : FeSetup;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_IO_State : STRUCT
    pMeth : ^CHMETH;
    dData : IO_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_IO_State : STRUCT
    pCh : ^SvrCh_IO_State;
    dData : IO_State;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_UDINT : STRUCT
    pMeth : ^CHMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_UDINT : STRUCT
    pCh : ^SvrCh_UDINT;
    dData : UDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CMDMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__AxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_AxisBase;
  END_STRUCT;
  SvrChCmd_DINT : STRUCT
    pMeth : ^CMDMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__Can : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Can;
  END_STRUCT;
  CltChCmd__CanLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_CanLib;
  END_STRUCT;
  CltChCmd__CheckSum : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_CheckSum;
  END_STRUCT;
  CltChCmd__FileSys : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_FileSys;
  END_STRUCT;
  CltChCmd__Linker : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Linker;
  END_STRUCT;
  CltChCmd__LMCABSEncoder : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCABSEncoder;
  END_STRUCT;
  CltChCmd__LMCAxis : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxis;
  END_STRUCT;
  CltChCmd__LMCAxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxisBase;
  END_STRUCT;
  CltChCmd__LMCAxisRef : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisRef;
  END_STRUCT;
  CltChCmd__LMCAxisVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVis;
  END_STRUCT;
  CltChCmd__LMCAxisVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisInt;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogHandle : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogHandle;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogViewer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogViewer;
  END_STRUCT;
  CltChCmd__LMCAxisVisPara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisPara;
  END_STRUCT;
  CltChCmd__LMCAxisVOVMonitoring : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVOVMonitoring;
  END_STRUCT;
  CltChCmd__LMCBaseCoord : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCBaseCoord;
  END_STRUCT;
  CltChCmd__LMCBeltAxis : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCBeltAxis;
  END_STRUCT;
  SvrChCmd_ProfileCommandStatus : STRUCT
    pMeth : ^CMDMETH;
    dData : ProfileCommandStatus;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__LMCCalcModelBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCCalcModelBase;
  END_STRUCT;
  CltChCmd__LMCCalcModelController : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCCalcModelController;
  END_STRUCT;
  CltChCmd__LMCMath_SO3 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCMath_SO3;
  END_STRUCT;
  CltChCmd__LMCMathFunctions : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCMathFunctions;
  END_STRUCT;
  CltChCmd__LMCProfileBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCProfileBase;
  END_STRUCT;
  CltChCmd__LMCProfileBuffer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileBuffer;
  END_STRUCT;
  CltChCmd__LMCProfileLog : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileLog;
  END_STRUCT;
  CltChCmd__LMCProfileVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVis;
  END_STRUCT;
  CltChCmd__LMCProfileVisAxis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisAxis;
  END_STRUCT;
  CltChCmd__LMCProfileVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisInt;
  END_STRUCT;
  CltChCmd__LMCProfileVisMovePara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisMovePara;
  END_STRUCT;
  CltChCmd__LMCPublisher : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCPublisher;
  END_STRUCT;
  CltChCmd__LMCRefBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCRefBase;
  END_STRUCT;
  CltChCmd__LMCRobotBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCRobotBase;
  END_STRUCT;
  CltChCmd__LMCRobotLog : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCRobotLog;
  END_STRUCT;
  CltChCmd__LMCSafety : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCSafety;
  END_STRUCT;
  CltChCmd__LMCSplineBuffer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCSplineBuffer;
  END_STRUCT;
  SvrChCmd_UDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__LMCTableBuffer : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^_LMCTableBuffer;
  END_STRUCT;
  CltChCmd__LMCTool : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCTool;
  END_STRUCT;
  CltChCmd__MultiTask : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_MultiTask;
  END_STRUCT;
  CltChCmd__OSKernel : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_OSKernel;
  END_STRUCT;
  CltChCmd__SerLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SerLib;
  END_STRUCT;
  CltChCmd__StdLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_StdLib;
  END_STRUCT;
  CltChCmd__SyncMeasureECAT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SyncMeasureECAT;
  END_STRUCT;
  CltChCmd__TaskObjectControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_TaskObjectControl;
  END_STRUCT;
  SvrChCmd__FSM_TCPIP_SERVER_PTofCls__TCPIPServer : STRUCT
    pMeth : ^CMDMETH;
    dData : _TCPIPServer::_FSM_TCPIP_SERVER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__TCPIPServer : STRUCT
    pCh : ^SvrChCmd__FSM_TCPIP_SERVER_PTofCls__TCPIPServer;
    dData : _TCPIPServer::_FSM_TCPIP_SERVER;
    pCmd : ^_TCPIPServer;
  END_STRUCT;
  CltChCmd_ASCII_BIN : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^ASCII_BIN;
  END_STRUCT;
  CltChCmd_Controller : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Controller;
  END_STRUCT;
  CltChCmd_CriticalSection : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^CriticalSection;
  END_STRUCT;
  CltChCmd_DiasMaster : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DiasMaster;
  END_STRUCT;
  CltChCmd_DiasMasterC : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DiasMasterC;
  END_STRUCT;
  CltChCmd_DiasMasterPostScan : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DiasMasterPostScan;
  END_STRUCT;
  CltChCmd_DINT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_EEPROM : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^EEPROM;
  END_STRUCT;
  CltChCmd_EtherCAT_Hub_Base : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^EtherCAT_Hub_Base;
  END_STRUCT;
  CltChCmd_GetCILInterface : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GetCILInterface;
  END_STRUCT;
  CltChCmd_Hub_Base : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Hub_Base;
  END_STRUCT;
  CltChCmd_Hub_Base_Root : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Hub_Base_Root;
  END_STRUCT;
  CltChCmd_HwcLogging : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HwcLogging;
  END_STRUCT;
  CltChCmd_HwControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HwControl;
  END_STRUCT;
  CltChCmd_HwControlBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HwControlBase;
  END_STRUCT;
  CltChCmd_HWRtPostScan : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^HWRtPostScan;
  END_STRUCT;
  CltChCmd_I2CCDIAS : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^I2CCDIAS;
  END_STRUCT;
  CltChCmd_Merker : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Merker;
  END_STRUCT;
  CltChCmd_MerkerEx : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^MerkerEx;
  END_STRUCT;
  CltChCmd_ProfileCommandStatus : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_RamFile : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RamFile;
  END_STRUCT;
  CltChCmd_SafetyManager : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SafetyManager;
  END_STRUCT;
  CltChCmd_SafetyRoutingTables : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SafetyRoutingTables;
  END_STRUCT;
  CltChCmd_SdiasHubBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SdiasHubBase;
  END_STRUCT;
  SvrChCmd_t_e_VaranErrors : STRUCT
    pMeth : ^CMDMETH;
    dData : t_e_VaranErrors;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_SdiasManager : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SdiasManager;
  END_STRUCT;
  CltChCmd_SigCLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SigCLib;
  END_STRUCT;
  CltChCmd_String : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^String;
  END_STRUCT;
  CltChCmd_StringInternal : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringInternal;
  END_STRUCT;
  SvrChCmd_IO_State : STRUCT
    pMeth : ^CMDMETH;
    dData : IO_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd_SyncCall : STRUCT
    pCh : ^SvrChCmd_IO_State;
    dData : IO_State;
    pCmd : ^SyncCall;
  END_STRUCT;
  CltChCmd_t_e_VaranErrors : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_Varan_Base : STRUCT
    pCh : ^SvrChCmd_t_e_VaranErrors;
    dData : t_e_VaranErrors;
    pCmd : ^Varan_Base;
  END_STRUCT;
  CltChCmd_VaranManager_Base : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^VaranManager_Base;
  END_STRUCT;
  CltChCmd_WatchdogDias : STRUCT
    pCh : ^SvrChCmd_IO_State;
    dData : IO_State;
    pCmd : ^WatchdogDias;
  END_STRUCT;
  CltChCmd_XXXBase_IOs : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^XXXBase_IOs;
  END_STRUCT;
  SvrCh__CommandList_PTofCls__LMCAxisBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAxisBase::_CommandList;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FSM_TCPIP_SERVER_PTofCls__TCPIPServer : STRUCT
    pMeth : ^CHMETH;
    dData : _TCPIPServer::_FSM_TCPIP_SERVER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyUDP::_FSM_UDP_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyUDP::_FSM_UDP_USER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__INITSTEPS_PTofCls_SafetyUDP : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyUDP::_INITSTEPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_CMDERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_CMDERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR_CONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR_CONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVE_RELATIVE_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVE_RELATIVE_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEDIRECTION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEDIRECTION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POSMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POSMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POWER_OFF_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POWER_OFF_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_REFMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_REFMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPOSITION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPOSITION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETSWENDPOS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETSWENDPOS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_STATUS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_STATUS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCCONTROLLERTYPE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCCONTROLLERTYPE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROF_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROF_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCIRCLEDEF : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCIRCLEDEF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRORTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRORTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRWARNCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRWARNCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFILESTATES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFILESTATES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFMOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFMOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERAXIS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERAXIS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERGROUPS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERGROUPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFTRANSMODES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFTRANSMODES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__POSFLAGS : STRUCT
    pMeth : ^CHMETH;
    dData : _POSFLAGS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__ROBOT_MODE_PTofCls__LMCRobotBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCRobotBase::_ROBOT_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__ROBOT_STATUS_PTofCls__LMCRobotBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCRobotBase::_ROBOT_STATUS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__STATE_TCPIP_INTF_PTofCls__TCPIPServerInterface : STRUCT
    pMeth : ^CHMETH;
    dData : _TCPIPServerInterface::_STATE_TCPIP_INTF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_DS402_Control : STRUCT
    pMeth : ^CHMETH;
    dData : DS402_Control;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_DS402_State : STRUCT
    pMeth : ^CHMETH;
    dData : DS402_State;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_HDINT : STRUCT
    pMeth : ^CHMETH;
    dData : HDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_SafetyConfigStateType : STRUCT
    pMeth : ^CHMETH;
    dData : SafetyConfigStateType;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_ECAT_STATE : STRUCT
    pMeth : ^CHMETH;
    dData : t_e_ECAT_STATE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_SafetyMemState : STRUCT
    pMeth : ^CHMETH;
    dData : t_e_SafetyMemState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_VaranErrors : STRUCT
    pMeth : ^CHMETH;
    dData : t_e_VaranErrors;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_s_LMCAxis_SafetyState_PTofCls__LMCAxisBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAxisBase::t_s_LMCAxis_SafetyState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrChCmd_iprStates : STRUCT
    pMeth : ^CMDMETH;
    dData : iprStates;
    pDsc : ^SVRDSC;
  END_STRUCT;
END_TYPE
