//This file was generated by the LASAL2 CodeGenerator  --
//Please, do not edit this file (it might be overwritten by the next generator run)
#RE_IN_DE
#pragma define (store)
#if _LSL_COMPILERVERSION >= 42
_LMCModuleBase : CLASS;
HwcLogging : CLASS;
SigCLib : CLASS;
#endif
_AxisBase : CLASS_PUBLIC
	TYPE
	  _LMCAXIS_POSINFOMODE :
	  (
	    POSINFO_TIME,
	    POSINFO_DISTANCE
	  )$UDINT;
	  _LMCAXIS_READPARAMETER_LREAL :
	  (
	    LMCAXIS_PAR_RD2_JMAX,
	    LMCAXIS_PAR_RD2_ACC
	  )$UDINT;
	  CmdControl :
	  (
	    IPRPowerOn,
	    IPRPowerOff,
	    IPRMoveRelative,
	    IPRMoveAbsolute,
	    IPRMoveReference,
	    IPRMoveEndless,
	    IPRMoveHand,
	    IPRStopMove,
	    IPRCoupleGearVelocity,
	    IPRCoupleDeltaPos,
	    IPRCoupleUserPos,
	    IPRCoupleProfilePos,
	    IPRCoupleGearRelative,
	    IPRCoupleGearAbsolute,
	    IPRCoupleCurveTab,
	    IPRSetSWEndPos,
	    IPRSetPosition,
	    IPRChangeCoupleSettings,
	    IPRTuneAxis,
	    IPRReadPosition,
	    IPRReadVelocity,
	    IPRInPosition,
	    IPRReadAxisStatus,
	    IPRReadAxisError,
	    IPRReadMasterInfo,
	    IPRSetFollowMode,
	    IPRReferenceReady,
	    IPRInpositionOk,
	    IPRCoupleGearPolynom,
	    IPRSetParameter,
	    IPRSetAdjustment,
	    IPRReadParameter,
	    IPRReadSWEndPos,
	    IPRCalcMovingTime,
	    IPRQuitError,
	    IPRCalcMaxSlavePath,
	    IPRCalcExtToAppliPos,
	    IPRReadUserData,
	    IPRGetMasterInformation,
	    IPR_SetErrorToMasterCoupleMonitoring,
	    IPRSetSafetyState,
	    IPRGetSafetyState
	  )$UINT;
	  t_e_LMCAXIS_GETSAFETYPARAMETER :  //! <Type Public   = "true" Comment  = "Public type which defines the allowed parameters of method GetSafetyData(). Check the comments of the single enum entries for more detailed information of the parameter.&#13;&#10;Available parameters:&#13;&#10;LMCAXIS_PAR_GET_SAFETY_SAFETYERROR - Reads the safety error information from either safety core 1 or safety core 2 (use mode to choose)&#13;&#10;LMCAXIS_PAR_GET_SAFETY_VERIFYSTATE - Reads the verify state of the connected axis. Does no trigger reading the a new value - the stored result of the hardware class is returned.&#13;&#10;LMCAXIS_PAR_GET_SAFETY_REFERENCESTATE - Reads the reference state of the connected axis. Does no trigger reading the a new value - the stored result of the hardware class is returned.&#13;&#10;LMCAXIS_PAR_GET_SAFETY_SBTSTATE - Reads the SBT state of the connected axis. Command triggers reading a new value by itself." Revision = "1.0" Name     = "t_e_LMCAXIS_GETSAFETYPARAMETER"> <RevDoku>  <Owner Company="Sigmatek"/>  <Dokumentation Revision="1.0" Date="2023-07-17" Author="StePhi" Company="Sigmatek" Description="Initial version of type"/> </RevDoku></Type>
	  (
	    LMCAXIS_PAR_GET_SAFETY_SAFETYERROR,
	    LMCAXIS_PAR_GET_SAFETY_SAFETYFUNCERROR,
	    LMCAXIS_PAR_GET_SAFETY_VERIFYSTATE,
	    LMCAXIS_PAR_GET_SAFETY_REFERENCESTATE,
	    LMCAXIS_PAR_GET_SAFETY_SBTSTATE,
	    LMCAXIS_PAR_GET_SAFETY_RUNSTATE,
	    LMCAXIS_PAR_GET_SAFETY_CNTRLSTATEWORD
	  )$UDINT;
	  t_e_LMCAXIS_SETSAFETYPARAMETER :  //! <Type Public   = "true" Comment  = "Public type which defines the allowed parameters of method SetSafetyData(). Check the comments of the single enum entries for more detailed information of the parameter.&#13;&#10;Available parameters:&#13;&#10;LMCAXIS_PAR_SET_SAFETY_SETVERIFY - Command sends a verify command to the connected axis. The command automatically reads the verify state afterwards.&#13;&#10;LMCAXIS_PAR_SET_SAFETY_CLEARVERIFY - Command sends a clear verify command to the connected axis. The command automatically reads the reference state afterwards.&#13;&#10;LMCAXIS_PAR_SET_SAFETY_CLEARREFERENCE - Command sends a clear reference command to the connected axis. The command automatically reads the reference state afterwards." Revision = "1.0" Name     = "t_e_LMCAXIS_SETSAFETYPARAMETER"> <RevDoku>  <Owner Company="Sigmatek"/>  <Dokumentation Revision="1.0" Date="2023-07-17" Author="StePhi" Company="Sigmatek" Description="Initial version of type"/> </RevDoku></Type>
	  (
	    LMCAXIS_PAR_SET_SAFETY_SETVERIFY,
	    LMCAXIS_PAR_SET_SAFETY_CLEARVERIFY,
	    LMCAXIS_PAR_SET_SAFETY_CLEARREFERENCE,
	    LMCAXIS_PAR_SET_SAFETY_QUITERROR,
	    LMCAXIS_PAR_SET_SAFETY_CHANGESERVICEMODE
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
_LMCRefBase : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  _LMCAXIS_REFDATA : STRUCT
	    Status : iprStates;
	    Velocity : DINT;
	    Acc : DINT;
	    vSetRef1 : DINT;
	    vSetRef2 : DINT;
	    PosWindow : DINT;
	    LatchPosRef : DINT;
	    Speed : DINT;
	  END_STRUCT;
#pragma pack(pop)
	  _LMCREF_READPARAMETER :
	  (
	    ZPULSE_DIST
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _LMCAxisBase
_LMCAxisBase : CLASS_PUBLIC
: _AxisBase
#include <.\lsl_st_systrace.h>
#include "..\Class\_LMCAxisBase\C_MathAxis.h"
#include "..\Class\_LMCAxisBase\_LMCTraceView.h"
#include "..\Class\_LMCAxisBase\BacklashLogin.h"
#include "..\Class\_LMCAxisBase\TorqueHandlingLogin.h"
	TYPE
	  _CommandList :
	  (
	    CPowerOn,
	    CPowerOff,
	    CInposition,
	    CMoveHand,
	    CMoveEndless,
	    CMoveAbsolut,
	    CMoveReference,
	    CMoveRelative,
	    CStopMove,
	    CCoupleGearAbsolute,
	    CCoupleGearRelative,
	    CCoupleGearVelocity,
	    CCoupleCurveTab,
	    CCoupleUserPos,
	    CCoupleUserPosExtended,
	    CCoupleDeltaPos,
	    CCoupleDeltaPosExtended,
	    CCoupleProfilePos,
	    CCoupleProfilePosExtended,
	    CSetPosition,
	    CSetAutoOffset,
	    CSetCoupleParameter,
	    CSetParameter,
	    CReadPosition,
	    CSetSWEndPos,
	    CReadSWEndPos,
	    CReadAxisError,
	    CReadAxisStatus,
	    CReadMasterInfo,
	    CReadVelocity,
	    CReadParameter,
	    CTuneAxis:=28,
	    CInternModuloOverFlow:=29,
	    CFollowMode:=30,
	    CCoupleGearPolynom:=31,
	    CCoupleAdditivePosDiff:=32,
	    CCoupleCAM,
	    CMoveShortestWay,
	    CCalcMovingTime,
	    CQuitError,
	    CCalcMaxSlavePath,
	    CCalcExtToAppliPos,
	    CChangeMoveSettings,
	    CGetPosInfoBeforeRampDown,
	    CSetDynSWEndPos,
	    CQuickStop,
	    CSetSafetyData,
	    CGetSafetyData,
	    CStorePosition:=1001,
	    CDeleteStoredData
	  )$UDINT;
	  _CoupleMonitorExtendedConfig : BDINT
	  [
	    1 ReportErrorToMaster,
	    2 ReportSlaveErrorToMaster,
	    3 ReportMasterErrorToSlave,
	    4 ReportSlaveErrorToSlave,
	    5 SwLimitMonitoring,
	    6 PowerOffMonitoring,
	  ];
	  _LogStruct : STRUCT
	    Command : _CommandList;
	    CommandoResult : _LMCAXIS_CMDERROR;
	    TimeStamp : UDINT;
	    RTStamp : UDINT;
	  END_STRUCT;
	  _LogFile : STRUCT
	    Logmode : DINT;
	    AccesNr : DINT;
	    LogData : ARRAY [0..101] OF _LogStruct;
	  END_STRUCT;
	  t_BLMMeasFlags : BINT
	  [
	    1 StartMeasurement,
	    2 DoMeasurement,
	    3 FinishedMeasurement,
	    4 BLValueDetected,
	    5 BLAmountNegCalced,
	    6 BLAmountPosCalced,
	    7 GetHWInfo,
	    8 HWInfoError,
	    9 DoBLValCorrection,
	    10 InvCurr,
	    11 Bit11,
	    12 Bit12,
	    13 Bit13,
	    14 Bit14,
	    15 Bit15,
	    16 DoMeasurementError,
	  ];
	  t_BLCCompFlags : BINT
	  [
	    1 DirFlg,
	    2 TransitionActive,
	    3 Enabled,
	    4 EnabledMarker,
	    5 UseTable,
	    6 CallTable,
	    7 CalcBL,
	    8 Standstill,
	    9 StandstillMarker,
	    10 MoveDirChanged,
	    11 ValidTable,
	    12 Bit12,
	    13 Bit13,
	    14 Bit14,
	    15 TransferBLAmountError,
	    16 ExecuteBacklashError,
	  ];
	  t_e_THCmdClassSvr :
	  (
	    IPRLMCTorqueHandling_CheckConnection:=91,
	    IPRLMCTorqueHandling_SetControlParas,
	    IPRLMCTorqueHandling_ExecutionState,
	    IPRLMCTorqueHandling_StoreMoveCommand,
	    IPRLMCTorqueHandling_GetDragPointer
	  )$UDINT;
	  t_s_LMCAxis_SafetyState : BDINT  //! <Type Public   = "true" Comment  = "Public type defining the safety axis state information of SafetyAxisState server." Revision = "1.0" Name     = "t_s_LMCAxis_SafetyState"> <RevDoku>  <Owner Company="Sigmatek"/>  <Dokumentation Revision="1.0" Date="2023-07-17" Author="StePhi" Company="Sigmatek" Description="Initial version of type"/> </RevDoku></Type>
	  [
	    1 SafeAxis,
	    2 SpeedLimited,
	    3 AxisReady,
	    4 AxisOperational,
	    5 AxisError,
	    6 ServiceModePending,
	    7 SafeErrorQuitPending,
	    8 AxisVerified,
	    9 AxisVerifyFailed,
	    10 AxisReferenced,
	    11 AxisReferenceActive,
	    12 AxisReferenceNeeded,
	    13 AxisReferenceFailed,
	    14 SBTAvailable,
	    15 SBTActive,
	    16 SBTFailed,
	    17 FSoESetupFailed,
	    18 AutomaticSS2Active,
	    19 SS2IsConfigured,
	  ];
	  te_BLCmdClassSvr :
	  (
	    IPBLCGetPointerBacklash:=51,
	    IPBLCSetBacklashAmount,
	    IPBLCGetPointerBLCompFlags,
	    IPBLCExecute,
	    IPBLCSetPointerSetPosVel,
	    IPBLCSetTimeBase,
	    IPBLCDetectMoveDirChange,
	    IPBLCReset,
	    IPBLMGetPointerBacklashValue:=71,
	    IPBLMDoMeasurement,
	    IPBLMGetPointerMeasFlags,
	    IPBLMSetTimeBase,
	    IPBLMSetExtIntUnits,
	    IPBLMSetPlaceAxisNo,
	    IPBLMSetCurrSign,
	    IPBLMReset
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _LMCMath_SO3
_LMCMath_SO3 : CLASS_PUBLIC
	TYPE
	  _ADVAN_MATRIX_ : ARRAY [0..2, 0..3] OF LREAL;
	  _FRAME_ : ARRAY [0..3, 0..3] OF LREAL;
#pragma pack(push, 1)
	  _VECTOR_ : STRUCT
	    v_x : LREAL;
	    v_y : LREAL;
	    v_z : LREAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _HOM_VEC_ : STRUCT
	    vec_r : _VECTOR_;
	    w : LREAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _POINT_ : STRUCT
	    e_x : DINT;
	    e_y : DINT;
	    e_z : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _ROT_GEOMETRY_ : STRUCT
	    Angle : DINT;
	    RotAxis : _POINT_;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _ROT_GEOMETRY_LREAL : STRUCT
	    phi : LREAL;
	    RotAxis : _VECTOR_;
	  END_STRUCT;
#pragma pack(pop)
	  _ROT_MODUS :
	  (
	    ACTIVE_ROTATION,
	    PASSIVE_ROTATION
	  )$UDINT;
	  _TENSOR_ : ARRAY [0..2, 0..2] OF LREAL;
	END_TYPE
END_CLASS;
#pragma define (restore)
_LMCBaseCoord : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  _ROT_ANGLE_ : STRUCT
	    Offset_RotateX : DINT;
	    Offset_RotateY : DINT;
	    Offset_RotateZ : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _TEACH_POINTS_ : STRUCT
	    Origin : _LMCMath_SO3::_POINT_;
	    Point_X : _LMCMath_SO3::_POINT_;
	    Point_XY : _LMCMath_SO3::_POINT_;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _LMCMathFunctions
_LMCMathFunctions : CLASS_PUBLIC
#include "..\Class\_LMCMathFunctions\C_MathFunct.h"
	TYPE
#pragma pack(push, 4)
	  _coeff_ : STRUCT
	    coA : LREAL;
	    coB : LREAL;
	    coC : LREAL;
	    coD : LREAL;
	    coE : LREAL;
	  END_STRUCT;
#pragma pack(pop)
	  _COORD_2D : ARRAY [0..1] OF DINT;
#pragma pack(push, 4)
	  _LMC_VECTOR3 : STRUCT
	    coord_x1 : LREAL;
	    coord_x2 : LREAL;
	    coord_x3 : LREAL;
	  END_STRUCT;
#pragma pack(pop)
	  t_e_LMC_MoveProf_Jerk_ProfTypes :
	  (
	    LMC_ProfType_Jerk_TT,
	    LMC_ProfType_Jerk_TW,
	    LMC_ProfType_Jerk_WW,
	    LMC_ProfType_Jerk_WT,
	    LMC_ProfType_Jerk_XW,
	    LMC_ProfType_Jerk_XT
	  )$UDINT;
	  t_e_LMCMath_Retcodes :
	  (
	    LMCMathRet_NoError,
	    LMCMathRet_NegRoot,
	    LMCMathRet_InputErr,
	    LMCMathRet_NotPossible
	  )$UDINT;
#pragma pack(push, 1)
	  t_st_LMC_MoveProf_Jerk_Point : STRUCT
	    lrT : LREAL;
	    lrS : LREAL;
	    lrV : LREAL;
	    lrA : LREAL;
	    lrJ : LREAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  t_st_LMC_MoveProf_Jerk : STRUCT
	    ProfileType : t_e_LMC_MoveProf_Jerk_ProfTypes;
	    aPts : ARRAY [0..9] OF t_st_LMC_MoveProf_Jerk_Point;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _LMCTableBuffer
_LMCTableBuffer : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  _CURVATURE_DATA : STRUCT
	    aPos : ARRAY [0..3] OF LREAL;
	    aCurvature : ARRAY [0..3] OF LREAL;
	    Typ : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _TableBufferEntry_ : STRUCT
	    XPos : LREAL;
	    YPos : LREAL;
	    ZPos : LREAL;
	    SplineArg : LREAL;
	    PathLength : LREAL;
	    Flexion : LREAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _Table_ : STRUCT
	    KoFacXStart : LREAL;
	    KoFacYStart : LREAL;
	    KoFacZStart : LREAL;
	    KoFacXEnd : LREAL;
	    KoFacYEnd : LREAL;
	    KoFacZEnd : LREAL;
	    udNumPoints : UDINT;
	    pDataPoints : ^_TableBufferEntry_;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _LMCSplineBuffer
_LMCSplineBuffer : CLASS_PUBLIC
	TYPE
	  t_e_SplineBufferParameters :
	  (
	    SBP_Timebase,
	    SBP_CalcPos,
	    SBP_CalcVel,
	    SBP_CalcAccel,
	    SBP_CalcJerk,
	    SBP_CalcJounce,
	    SBP_MaxIterations,
	    SBP_SearchWindow
	  )$UDINT;
	  t_e_SplineCheckResults :
	  (
	    SCR_OK,
	    SCR_InputError,
	    SCR_VelError,
	    SCR_AccError,
	    SCR_JerkError
	  )$UDINT;
	  t_e_SplineConfirmations :
	  (
	    SC_Symmetrical,
	    SC_Linear
	  )$UDINT;
#pragma pack(push, 1)
	  t_st_SplineCoefficients : STRUCT
	    lrCoefficient1 : LREAL;
	    lrCoefficient2 : LREAL;
	    lrCoefficient3 : LREAL;
	    lrCoefficient4 : LREAL;
	    lrCoefficient5 : LREAL;
	    lrCoefficient6 : LREAL;
	    lrCoefficient7 : LREAL;
	    lrCoefficient8 : LREAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  t_st_SplineEntry : STRUCT
	    lrDuration : LREAL;
	    lrPos : LREAL;
	    lrVel : LREAL;
	    lrAccel : LREAL;
	    lrJerk : LREAL;
	    lrJounce : LREAL;
	    lrTick : LREAL;
	    Coefficients : t_st_SplineCoefficients;
	    bdSplineConfig : BDINT
	    [
	      1 bInPos,
	      2 Bit2,
	      3 Bit3,
	      4 Bit4,
	      5 Bit5,
	      6 Bit6,
	      7 Bit7,
	      8 Bit8,
	      9 Bit9,
	      10 Bit10,
	      11 Bit11,
	      12 Bit12,
	      13 Bit13,
	      14 Bit14,
	      15 Bit15,
	      16 Bit16,
	      17 Bit17,
	      18 Bit18,
	      19 Bit19,
	      20 Bit20,
	      21 Bit21,
	      22 Bit22,
	      23 Bit23,
	      24 Bit24,
	      25 Bit25,
	      26 Bit26,
	      27 Bit27,
	      28 Bit28,
	      29 Bit29,
	      30 Bit30,
	      31 Bit31,
	      32 Bit32,
	    ];
	  END_STRUCT;
#pragma pack(pop)
	  t_p_st_SplineEntry : ^t_st_SplineEntry;
#pragma pack(push, 1)
	  t_st_SplineGroup : STRUCT
	    udTick : UDINT;
	    udNumSplines : UDINT;
	    udLastSpline : UDINT;
	    aSplines : ARRAY [0..LMCSPLINEBUFF_MAX_SPLINES_PER_GROUP-1] OF t_st_SplineEntry;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _LMCProfileBase
_LMCProfileBase : CLASS_PUBLIC
#include <.\lsl_st_systrace.h>
#include "..\Class\_LMCProfileBase\C_MathProfile.h"
#include "..\Class\_LMCAxisBase\_LMCTraceView.h"
	TYPE
	  _LMCPROFTRANSMODESINT :
	  (
	    _LMC_EXACT_STOP,
	    _LMC_CONT_DIRECT_ACTIVE,
	    _LMC_CONT_DIRECT,
	    _LMC_SMOOTH_PARAB,
	    _LMC_SMOOTH_CUBIC,
	    _LMC_SMOOTH_5TH,
	    _LMC_SMOOTH_CLOTH
	  )$UDINT;
#pragma pack(push, 4)
	  _LMCPROF_POSITIONS_INTERN : STRUCT
	    start : LREAL;
	    end : LREAL;
	  END_STRUCT;
#pragma pack(pop)
	  _LMCPROFAXISDATA : STRUCT
	    pos : _LMCPROF_POSITIONS_INTERN;
	    KoA : LREAL;
	    KoE : LREAL;
	    KoAorth : LREAL;
	    KoEorth : LREAL;
	    a1 : LREAL;
	    a2 : LREAL;
	    a3 : LREAL;
	    a4 : LREAL;
	    a5 : LREAL;
	    isCloth : UDINT;
	  END_STRUCT;
	  _LMCPROF_CIRC_DEF_INTERN : BDINT
	  [
	    1 Axis1,
	    2 Axis2,
	    3 Axis3,
	    4 Axis4,
	    5 Axis5,
	    6 Axis6,
	    7 Axis7,
	    8 Axis8,
	    9 Axis9,
	    17 CircleCCW,
	  ];
	  _LMCPROFCIRCLEINDEXDEF : ARRAY [0.._LMC_MAX_AXIS-1] OF USINT;
	  _LMCPROFCIRCLEPLAINE :
	  (
	    NO_CIRCLE,
	    CIRCLE_2_AXIS,
	    CIRCLE_3_AXIS
	  )$UDINT;
#pragma pack(push, 4)
	  _LMCPROFCIRCLEDATA : STRUCT
	    xmp : DINT;
	    ymp : DINT;
	    zmp : DINT;
	    xstart : LREAL;
	    ystart : LREAL;
	    zstart : LREAL;
	    xortho : LREAL;
	    yortho : LREAL;
	    zortho : LREAL;
	    Radius : LREAL;
	    RadiusKor : LREAL;
	    ResidAngel : LREAL;
	    AlphaAnf : LREAL;
	    DeltaAlpha : LREAL;
	    CirclePlane : _LMCPROFCIRCLEPLAINE;
	    bIPnil : BOOL;
	    Interpoint : _LMCPROF_CIRCLEPOINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
	  _LMCPROF_MoveData_Intern : STRUCT
	    pUserBuffer : ^_LMCPROF_MoveData;
	    pUserBufferNext : ^_LMCPROF_MoveData;
	    pPrevMoveUncommon : ^_LMCPROF_MoveData_Intern;
	    pNextMoveUncommon : ^_LMCPROF_MoveData_Intern;
	    enCmdType : _LMCPROFCMDTYPES_INTERN;
	    enTransitionMode : _LMCPROFTRANSMODESINT;
	    dTransitionRadius : DINT;
	    bdCmdFlags : _LMCPROFINTCMDCONFIG_THREADSAFE;
	    stData : ARRAY [0.._LMC_MAX_AXIS-1] OF _LMCPROFAXISDATA;
	    ArcLength : LREAL;
	    PathLength : LREAL;
	    GroupPath : USINT;
	    bdCirAxis : _LMCPROF_CIRC_DEF_INTERN;
	    arCirIndex : _LMCPROFCIRCLEINDEXDEF;
	    stCirData : _LMCPROFCIRCLEDATA;
	    Vmax : LREAL;
	    Amax : LREAL;
	    Dmax : LREAL;
	    JMax : LREAL;
	    vNext : LREAL;
	    vNextLimit : LREAL;
	    vLimitDef : LREAL;
	    vLimit : LREAL;
	    vFStart : LREAL;
	    vFEnd : LREAL;
	    CoordSysNr : DINT;
	    PosSwMin : DINT;
	    PosSwMax : DINT;
	    SpecificMoveData : ARRAY [0..35] OF USINT;
	    Obstacle : _LMCPROF_OBSTACLE;
	    SplineCornerOverdrive : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _SpecMoveData_MoveCurve : STRUCT
	    pTable : ^_LMCTableBuffer::_Table_;
	    dCurvatureIndex : DINT;
	    pSplineGroup : ^_LMCSplineBuffer::t_st_SplineGroup;
	    bSplineVelocity : BOOL;
	    bSwitchToJerk : BOOL;
	  END_STRUCT;
#pragma pack(pop)
	  t_e_SpaceSection :
	  (
	    SS_Undefined,
	    SS_PlaneXY_1,
	    SS_PlaneXY_2,
	    SS_PlaneXY_3,
	    SS_PlaneXY_4,
	    SS_PlaneXZ_1,
	    SS_PlaneXZ_2,
	    SS_PlaneXZ_3,
	    SS_PlaneXZ_4,
	    SS_PlaneYZ_1,
	    SS_PlaneYZ_2,
	    SS_PlaneYZ_3,
	    SS_PlaneYZ_4,
	    SS_LineX,
	    SS_LineY,
	    SS_LineZ,
	    SS_Cube1,
	    SS_Cube2,
	    SS_Cube3,
	    SS_Cube4,
	    SS_Cube5,
	    SS_Cube6,
	    SS_Cube7,
	    SS_Cube8
	  )$UDINT;
#pragma pack(push, 1)
	  _SpecMoveData_MoveLinear : STRUCT
	    pSplineGroup : ^_LMCSplineBuffer::t_st_SplineGroup;
	    TargetSection : t_e_SpaceSection;
	    lrBendAngle : LREAL;
	    bSplineVelocity : BOOL;
	    bSwitchToJerk : BOOL;
	  END_STRUCT;
#pragma pack(pop)
	  CmdControl :
	  (
	    IPRSetBasicParameter,
	    IPRLockProfile,
	    IPRUnlockProfile,
	    IPRMoveLiniare,
	    IPRMoveCircle,
	    IPRProfileInPos,
	    IPRReadPos,
	    IPRProfileFinished,
	    IPRInitPosWin,
	    IPRProfAxisFinished,
	    IPRProfAxisInPos,
	    IPRPofChkType,
	    IPRPRofReadActError,
	    IPRProfReadLastIndex,
	    IPRProfDefMoveCircle,
	    IPRProfMoveFinished,
	    IPRProfGetStartpos,
	    IPRProfGetFreeLines,
	    IPRProfGetResidualPath,
	    IPRProfStopMove,
	    IPRProfRestartMove,
	    IPRProfIsProfileStopped,
	    IPRProfReadActPosition,
	    IPRProfSetOverride,
	    IPRProfReadOverride,
	    IPRProfReadEntryIndex,
	    IPRProfReadActSubError,
	    IPRSetAxisParameter,
	    IPRSetProfileParameter,
	    IPRCoupleGearAbsolute,
	    IPRCoupleGearRelative,
	    IPRCoupleGearVelocity,
	    IPRCoupleCurveTab,
	    IPRCoupleUserPos,
	    IPRCoupleProfilePos,
	    IPRCoupleGearPolynom,
	    IPRReadAxisState,
	    IPRGetBrakePositions,
	    IPRGetLinBrakePoint,
	    IPRGetRotBrakePoint,
	    IPRReadCmdIndex,
	    IPRReadProfileActValues,
	    IPRGetMoveFinished,
	    IPRReadResidualTime,
	    IPRGetBufferData,
	    IPRReadTimebase,
	    IPRProfileMoveRelative,
	    IPRLockProfileRestart,
	    IPRLockProfileStartLineNo,
	    IPRSetRestartPointIPR,
	    IPRReadRestartPos,
	    IPRContinueNCProg,
	    IPRReadRestartInfo,
	    IPRProfGetStartposRestart,
	    IPRReadCommonCalcParas,
	    IPRLockProfileStartFileOffset,
	    IPRLockProfileRestartFileOffset,
	    IPRSetRestartPoint,
	    IPRSetAxesPositionsG92,
	    IPRSetAxesPositionsG92Live,
	    IPRSetProfileInPos,
	    IPRReadProfileActValuesLREAL,
	    IPRActivateCmdByLMCCNCIpr,
	    IPRSetLMCCNCIprMode,
	    IPRIsRestartPointReached,
	    IPRReadLastPathLength,
	    IPRFinishCmd,
	    IPRGetDestinationPos,
	    IPRStopMoveEndOfMovement,
	    IPRRecalcVelocity,
	    IPRSetAxesPositionsG92Immediate,
	    IPRTangAxisConfig,
	    IPRTangAxisActivate,
	    IPRTangAxisDeactivate,
	    IPRGetMaxBufferSize,
	    IPRMoveSpline,
	    IPRGetNoMainAxes,
	    IPRProfStopMoveDecel,
	    IPRLimitProfileDynamics,
	    IPRDynamicPositionCorrection,
	    IPRGetBufferData_EndPos,
	    IPRGetBufferData_VMax
	  )$UINT;
	  t_s_PartialDynParaLimitModes : BDINT
	  [
	    1 Activate,
	    2 UseLimitStopMove,
	  ];
	END_TYPE
END_CLASS;
#pragma define (restore)
_LMCProfileBuffer : CLASS_PUBLIC
	TYPE
	  _BUFFER_PARAMETER_ :
	  (
	    Max_Entries,
	    HiRes,
	    MaxEntries_TmpBuffer,
	    LMCCNC_IPR_MODE,
	    MaxEntries_RstrtBuffer,
	    ReverseActive
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
MoveSplineTable : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  t_SplinePoint : STRUCT
	    Index : DINT;
	    Point : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  t_SplineMove : STRUCT
	    MoveIdx : DINT;
	    PointLastIdx : DINT;
	    pFirstPoint : ^t_SplinePoint;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk _LMCProfileLog
_LMCProfileLog : CLASS_PUBLIC
	TYPE
	  _LMCLogCmdList :
	  (
	    CEmpty,
	    CSetBasicParameter,
	    CLockProfile,
	    CUnlockProfile,
	    CMoveLinear,
	    CMoveCircle,
	    CMoveRelative,
	    CCircleDefinition,
	    CStopMove,
	    CSetAxisParameter,
	    CReadAxisParameter,
	    CSetGroupParameter,
	    CReadGroupParameter,
	    CSetProfileParameter,
	    CReadProfileParameter,
	    CProfileInPosition,
	    CReadPosition,
	    CReadProfileError,
	    CGetStartPositions,
	    CGetSlowestAxis,
	    CSetTimeBase,
	    CGetMoveFinished,
	    CGetBufferData,
	    CReadPosOffset,
	    CSetPosOffset,
	    CCalcResidualTime,
	    CCoupleGearAbsolute,
	    CCoupleGearRelative,
	    CCoupleGearVelocity,
	    CCoupleCurveTab,
	    CCoupleUserPos,
	    CCoupleProfilePos,
	    CCoupleGearPolynom,
	    CReadAxisState,
	    CReadCmdIndex,
	    CSetDynSWEndPos,
	    CReadProfileActValues,
	    CGetBrakePositions,
	    CChangeCoupleSettings,
	    CCoupleAdditivePosDiff,
	    CGetRemotePoint,
	    CLockProfileRestart,
	    CLockProfileStartLineNo,
	    CSetRestartPoint,
	    CReadRestartPos,
	    CContinueNCProg,
	    CReadRestartInfo,
	    CGetStartPositionsRestart,
	    CReadCommonCalcParas,
	    CSetProfilePositions,
	    CRobotOn,
	    CRobotOff,
	    CRobotIsOn,
	    CMoveLinearBelt,
	    CMoveRelativeTCP,
	    CGetRobotPosition,
	    CReadRobotParameter,
	    CSetRobotParameter,
	    CAxMoveHand,
	    CAxMoveEndless,
	    CAxMoveAbsolute,
	    CAxMoveShortestWay,
	    CAxMoveReference,
	    CAxMoveRelative,
	    CAxStopMove,
	    CAxTuneAxis,
	    CAxSetPosition,
	    CAxQuitError,
	    CAxReadAxisError,
	    CAxReadParameter,
	    CAxReadSWEndPos,
	    CAxInPosition,
	    CAxSetParameter,
	    CGetAxInformation,
	    CLockProfileStartFileOffset,
	    CLockProfileRestartFileOffset,
	    CSetRestartPointFileOffset,
	    CAxReadPosition,
	    CAxSetFollowMode,
	    CMoveCurve,
	    CMoveCurveBelt,
	    CMoveCurveSpline,
	    CMoveCurveSplineBelt,
	    CAxSetAdjustment,
	    CMoveEndless,
	    CStretchLastMove,
	    CLockProfileRestartAfterStop,
	    CMoveRelativeCoord,
	    CMoveLinearCoord,
	    CMoveEndlessCoord,
	    CMoveCurveSplineCoord,
	    CMoveCurveCoord,
	    CMoveCircleCoord,
	    CReadProfileActValuesLREAL,
	    CGetBrakePositionsIntern,
	    CClothoidCircle,
	    CMoveSpline
	  )$UDINT;
#pragma pack(push, 1)
	  _LogStruct : STRUCT
	    CmdCode : _LMCLogCmdList;
	    RetCode : _LMCPROFERRORTYPES;
	    TimeStamp : UDINT;
	    CmdParameter : ARRAY [0..140] OF SINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogFile : STRUCT
	    LogData : ARRAY [0..MAX_LOG_BUFFER_INDEX+1] OF _LogStruct;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCalcResidualTime : STRUCT
	    Mode : _LMCPROF_RESTIME_CALCMODE;
	    ResidualTime : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParChangeCoupleSettings : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    DeltaPos : DINT;
	    GearMul : DINT;
	    GearDiv : DINT;
	    MaxJerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCircleDefinition : STRUCT
	    CircleDef : _LMCPROFCIRCLEDEF;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParContinueNCProg : STRUCT
	    PosWindow : DINT;
	    DelayTime : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleAdditivePosDiff : STRUCT
	    AxisNo : DINT;
	    pPosdiff : ^DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleCurveTab : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    DeltaPos : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	    Mode : _LMCAXIS_CURVETABMODE;
	    pCurveData : ^_LMCAXIS_CURVE;
	    MaxJerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearAbsolute : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    DeltaPos : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	    MaxJerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearPolynom : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	    sMaster : DINT;
	    sSlave : DINT;
	    MaxJerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearRelative : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	    MaxJerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearVelocity : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	    MaxJerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleProfilePos : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    Mode : _LMCPROF_RECOUPLEMODE;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleUserPos : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMasterPos : ^DINT;
	    DeltaPos : DINT;
	    GearMul : DINT;
	    GearDiv : DINT;
	    Mode : _LMCAXIS_COUPLE_GEAR_MODE;
	    MaxJerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetBrakePositions : STRUCT
	    Pos : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetBufferData : STRUCT
	    index : UDINT;
	    MoveData : _LMCPROF_MoveData;
	    RetCode : iprStates;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetMoveFinished : STRUCT
	    index : UDINT;
	    RetCode : iprStates;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetRemotePoint : STRUCT
	    RemoteDist : DINT;
	    RemoteTime : DINT;
	    ActualVel : DINT;
	    RemoteVel : DINT;
	    ActualAccel : DINT;
	    ProfileAccel : DINT;
	    Tjerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetSlowestAxis : STRUCT
	    Dest : _LMCPROF_POS;
	    usAxis : USINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetStartPositions : STRUCT
	    StartPos : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetStartPositionsRestart : STRUCT
	    StartPos : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParLockProfile : STRUCT
	    Axis1 : DINT;
	    Axis2 : DINT;
	    Axis3 : DINT;
	    Axis4 : DINT;
	    Axis5 : DINT;
	    Axis6 : DINT;
	    Axis7 : DINT;
	    Axis8 : DINT;
	    Axis9 : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParLockProfileRestart : STRUCT
	    Axis1 : DINT;
	    Axis2 : DINT;
	    Axis3 : DINT;
	    Axis4 : DINT;
	    Axis5 : DINT;
	    Axis6 : DINT;
	    Axis7 : DINT;
	    Axis8 : DINT;
	    Axis9 : DINT;
	    PathOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParLockProfileStartLineNo : STRUCT
	    Axis1 : DINT;
	    Axis2 : DINT;
	    Axis3 : DINT;
	    Axis4 : DINT;
	    Axis5 : DINT;
	    Axis6 : DINT;
	    Axis7 : DINT;
	    Axis8 : DINT;
	    Axis9 : DINT;
	    PathOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveCircle : STRUCT
	    Positions : _LMCPROF_POS;
	    MiddlePoint : _LMCPROF_CIRCLEPOINT;
	    InterPoint : _LMCPROF_CIRCLEPOINT;
	    CircleDef : _LMCPROFCIRCLEDEF;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveCurve : STRUCT
	    Positions : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Obstacle : _LMCPROF_OBSTACLE;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveCurveSpline : STRUCT
	    Positions : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    Jerk : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Obstacle : _LMCPROF_OBSTACLE;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveLinear : STRUCT
	    Positions : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveRelative : STRUCT
	    Distances : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParProfileInPosition : STRUCT
	    Mode : _LMCPROFINPOSTYPES;
	    RetCode : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadAxisParameter : STRUCT
	    AxisNo : DINT;
	    ParNo : _LMCPROFPARAMETERAXIS;
	    RetValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadAxisState : STRUCT
	    AxisNo : DINT;
	    AxisState : _LMCAXIS_STATUS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadCmdIndex : STRUCT
	    Mode : _LMCPROF_CMDINDEX;
	    Index : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadCommonCalcParas : STRUCT
	    CalcParas : _LMCCommonCalcParas;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _logParReadGroupParameter : STRUCT
	    GrpNo : DINT;
	    ParNo : _LMCPROFPARAMETERGROUPS;
	    RetValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadPosition : STRUCT
	    AxisNo : DINT;
	    Mode : DINT;
	    Position : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadPosOffset : STRUCT
	    PosOffset : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadProfileActValues : STRUCT
	    Mode : _LMCPROF_ACTUALVALUES;
	    ActualValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadProfileError : STRUCT
	    ErrorInfo : _LMCPROFERRORDEF;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadProfileParameter : STRUCT
	    ParNo : _LMCPROFPARAMETER;
	    RetValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadRestartInfo : STRUCT
	    sRestart : LREAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _logParReadRestartPos : STRUCT
	    Positions : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetAxisParameter : STRUCT
	    AxisNo : DINT;
	    ParNo : _LMCPROFPARAMETERAXIS;
	    Value : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetBasicParameter : STRUCT
	    VMax : DINT;
	    AMax : DINT;
	    Tjerk : DINT;
	    TangError : DINT;
	    PosOffset : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetDynSWEndPos : STRUCT
	    AxNo : DINT;
	    pSWEndPos : ^DINT;
	    Mode : _LMC_DYN_SWLIMITS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetGroupParameter : STRUCT
	    GrpNo : DINT;
	    ParNo : _LMCPROFPARAMETERGROUPS;
	    Value : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetPosOffset : STRUCT
	    PosOffset : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetProfileParameter : STRUCT
	    ParNo : _LMCPROFPARAMETER;
	    Value : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetProfilePositions : STRUCT
	    Mode : _LMCPROF_SETPOS_MODE;
	    pApproxPos : ^_LMCPROF_POS;
	    pCallbackData : pVoid;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetRestartPointFileOffset : STRUCT
	    PathOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetTimeBase : STRUCT
	    udTimeBase : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParStopMove : STRUCT
	    Mode : DINT;
	    Decel : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
	  _LogParStretchLastMove : STRUCT
	    FactorMul : UDINT;
	    FactorDiv : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
_LMCPublisher : CLASS_PUBLIC
	TYPE
	  _Config_ : BDINT
	  [
	    1 VirtualAxis,
	    2 RealAxis,
	  ];
	  _LMCPublisher_Cmd :
	  (
	    _LOGINCMD:=123
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
_LMCRobotBase : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  _AXDATA_ENTRY : STRUCT
	    ThisPtr : ^_AxisBase;
	    Config : BDINT
	    [
	      1 AxConnected,
	      2 ProfileAxis,
	      3 KinematicAxis,
	    ];
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _BELT_COUPLE_DATA : STRUCT
	    CoordSystem : DINT;
	    BeltDirection : DINT;
	    DesyncStart : DINT;
	    DesyncLength : DINT;
	    SyncStart : DINT;
	    SyncLength : DINT;
	    pMaster : ^MasterStruct;
	    BeltOffset : DINT;
	    GearMul : DINT;
	    GearDiv : DINT;
	  END_STRUCT;
#pragma pack(pop)
	  _ROBOT_MODE :
	  (
	    _ROBOT_PASSIVE,
	    _ROBOT_ACTIVE,
	    _ROBOT_DIRECT,
	    _ROBOT_ERROR,
	    _ROBOT_MODE_CHANGE
	  )$UDINT;
	  _PARAMETER :
	  (
	    _TIMEOUTS,
	    _ROBOT_STATE,
	    _DELAYED_MASTERLOCK,
	    _BELTCOUPLING_VEL_FILTER_DEPTH,
	    _STOPMOVE_POSITIONWINDOW,
	    _IS_CALCMODEL_CONNECTED,
	    _AXCOUNT_PROFILE,
	    _AXCOUNT_CALCMODEL,
	    _NOT_CALC_BOTH_KINEMATICS_OPTIMIZE,
	    _START_COUPLEWINDOW,
	    _MOVECURVE_EXTRA,
	    _ROTAXIS_GEAR_FACTOR,
	    _ROTDISC_MOVE_DIR
	  )$UDINT;
	  _POSITION_MODE :
	  (
	    _ACTPOS_APPUNITS,
	    _SETPOS_APPUNITS,
	    _PROFILE_POS_APPUNITS,
	    _ACTPOS_CALCMODEL_MOTORS,
	    _SETPOS_CALCMODEL_MOTORS
	  )$UDINT;
	  _ROBOT_ON_MODE :
	  (
	    _ACTIVE,
	    _DIRECT,
	    _NO_AXES_POWERON
	  )$UDINT;
	  _ROBOT_STATUS : BDINT
	  [
	    1 RobotIsOn,
	    2 IsReferenced,
	    3 LockedToBelt,
	    4 PowerIsOn,
	    5 PosLimActive,
	    6 NegLimActive,
	    7 BeltCouplingActive,
	  ];
	END_TYPE
END_CLASS;
#pragma define (restore)
_LMCRobotLog : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  _LogParAxInPosition : STRUCT
	    AxisNo : DINT;
	    Mode : _LMCAXIS_QUERY_POSITION_MODE;
	    PositionWindow : DINT;
	    Result : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxMoveAbsolute : STRUCT
	    AxisNo : DINT;
	    Position : DINT;
	    Speed : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxMoveEndless : STRUCT
	    AxisNo : DINT;
	    Speed : DINT;
	    Accel : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxMoveHand : STRUCT
	    AxisNo : DINT;
	    Speed : DINT;
	    Accel : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxMoveReference : STRUCT
	    AxisNo : DINT;
	    Mode : _LMCAXIS_REFMODE;
	    Position : DINT;
	    VRef1 : DINT;
	    VRef2 : DINT;
	    Accel : DINT;
	    PositionWindow : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxMoveRelative : STRUCT
	    AxisNo : DINT;
	    Position : DINT;
	    Mode : _LMCAXIS_MOVE_RELATIVE_MODE;
	    Speed : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxMoveShortestWay : STRUCT
	    AxisNo : DINT;
	    Position : DINT;
	    Speed : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxQuitError : STRUCT
	    AxisNo : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxReadAxisError : STRUCT
	    AxisNo : DINT;
	    AxisErrorInfo : _LMCAXIS_ERROR;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxReadParameter : STRUCT
	    AxisNo : DINT;
	    ParNr : _LMCAXIS_READPARAMETER;
	    mode : DINT;
	    Result : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxReadPosition : STRUCT
	    AxisNo : DINT;
	    Mode : _LMCAXIS_READPOS;
	    Position : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxReadSWEndPos : STRUCT
	    AxisNo : DINT;
	    Mode : _LMCAXIS_READSWENDPOS;
	    Position : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxSetFollowMode : STRUCT
	    AxisNo : DINT;
	    Mode : _LMCAXIS_FOLLOW_MODE;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxSetParameter : STRUCT
	    AxisNo : DINT;
	    ParNo : _LMCAXIS_SETPARAMETER;
	    Value : DINT;
	    Mode : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxSetPosition : STRUCT
	    AxisNo : DINT;
	    Mode : _LMCAXIS_SETPOSITION;
	    Position : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxStopMove : STRUCT
	    AxisNo : DINT;
	    Decel : DINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParAxTuneAxis : STRUCT
	    AxisNo : DINT;
	    Position : DINT;
	    Speed : DINT;
	    Accel : DINT;
	    Mode : _LMCAXIS_TUNE_MODE;
	    WaitTime : UDINT;
	    Jerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCalcResidualTime : STRUCT
	    Mode : _LMCPROF_RESTIME_CALCMODE;
	    ResidualTime : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParChangeCoupleSettings : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    DeltaPos : DINT;
	    GearMul : DINT;
	    GearDiv : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCircleDefinition : STRUCT
	    CircleDef : _LMCPROFCIRCLEDEF;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParContinueNCProg : STRUCT
	    PosWindow : DINT;
	    DelayTime : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleAdditivePosDiff : STRUCT
	    AxisNo : DINT;
	    pPosdiff : ^DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleCurveTab : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    DeltaPos : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	    Mode : _LMCAXIS_CURVETABMODE;
	    pCurveData : ^_LMCAXIS_CURVE;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearAbsolute : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    DeltaPos : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearPolynom : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	    sMaster : DINT;
	    sSlave : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearRelative : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleGearVelocity : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMaster : ^MasterStruct;
	    GearMul : DINT;
	    GearDiv : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleProfilePos : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    Mode : _LMCPROF_RECOUPLEMODE;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParCoupleUserPos : STRUCT
	    AxisNo : DINT;
	    CoupleMode : _LMCPROF_EXECUTE;
	    MaxVel : DINT;
	    MaxAcc : DINT;
	    pMasterPos : ^DINT;
	    DeltaPos : DINT;
	    GearMul : DINT;
	    GearDiv : DINT;
	    Mode : _LMCAXIS_COUPLE_GEAR_MODE;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetAxInformation : STRUCT
	    AxisNo : DINT;
	    pAxData : ^_LMCRobotBase::_AXDATA_ENTRY;
	    Result : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetBrakePositions : STRUCT
	    Pos : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetBufferData : STRUCT
	    index : UDINT;
	    MoveData : _LMCPROF_MoveData;
	    RetCode : iprStates;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetMoveFinished : STRUCT
	    index : UDINT;
	    RetCode : iprStates;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetRemotePoint : STRUCT
	    RemoteDist : DINT;
	    RemoteTime : DINT;
	    ActualVel : DINT;
	    RemoteVel : DINT;
	    ActualAccel : DINT;
	    ProfileAccel : DINT;
	    Tjerk : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetRobotPosition : STRUCT
	    Mode : _LMCRobotBase::_POSITION_MODE;
	    IncludeTool : BOOL;
	    CoordSystem : DINT;
	    Positions : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetSlowestAxis : STRUCT
	    Dest : _LMCPROF_POS;
	    usAxis : USINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetStartPositions : STRUCT
	    StartPos : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParGetStartPositionsRestart : STRUCT
	    StartPos : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParLockProfile : STRUCT
	    Axis1 : DINT;
	    Axis2 : DINT;
	    Axis3 : DINT;
	    Axis4 : DINT;
	    Axis5 : DINT;
	    Axis6 : DINT;
	    Axis7 : DINT;
	    Axis8 : DINT;
	    Axis9 : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParLockProfileRestart : STRUCT
	    Axis1 : DINT;
	    Axis2 : DINT;
	    Axis3 : DINT;
	    Axis4 : DINT;
	    Axis5 : DINT;
	    Axis6 : DINT;
	    Axis7 : DINT;
	    Axis8 : DINT;
	    Axis9 : DINT;
	    PathOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParLockProfileStartLineNo : STRUCT
	    Axis1 : DINT;
	    Axis2 : DINT;
	    Axis3 : DINT;
	    Axis4 : DINT;
	    Axis5 : DINT;
	    Axis6 : DINT;
	    Axis7 : DINT;
	    Axis8 : DINT;
	    Axis9 : DINT;
	    PathOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveCircle : STRUCT
	    Positions : _LMCPROF_POS;
	    MiddlePoint : _LMCPROF_CIRCLEPOINT;
	    InterPoint : _LMCPROF_CIRCLEPOINT;
	    CircleDef : _LMCPROFCIRCLEDEF;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveCurve : STRUCT
	    Positions : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Obstacle : _LMCPROF_OBSTACLE;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveCurveBelt : STRUCT
	    Positions : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Obstacle : _LMCPROF_OBSTACLE;
	    BeltData : _LMCRobotBase::_BELT_COUPLE_DATA;
	    Jerk : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveLinear : STRUCT
	    Positions : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveLinearBelt : STRUCT
	    Positions : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    BeltData : _LMCRobotBase::_BELT_COUPLE_DATA;
	    Jerk : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveRelative : STRUCT
	    Distances : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Jerk : DINT;
	    SetCoordSystem : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParMoveRelativeTCP : STRUCT
	    Distances : _LMCPROF_POS;
	    CmdConfig : _LMCPROFCMDCONFIG;
	    Velocity : DINT;
	    Accel : DINT;
	    Decel : DINT;
	    TransMode : _LMCPROFTRANSMODES;
	    TransRadius : DINT;
	    Jerk : DINT;
	    ActiveTool : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParProfileInPosition : STRUCT
	    Mode : _LMCPROFINPOSTYPES;
	    RetCode : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadAxisParameter : STRUCT
	    AxisNo : DINT;
	    ParNo : _LMCPROFPARAMETERAXIS;
	    RetValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadAxisState : STRUCT
	    AxisNo : DINT;
	    AxisState : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadCmdIndex : STRUCT
	    Mode : _LMCPROF_CMDINDEX;
	    Index : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadCommonCalcParas : STRUCT
	    CalcParas : _LMCCommonCalcParas;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _logParReadGroupParameter : STRUCT
	    GrpNo : DINT;
	    ParNo : _LMCPROFPARAMETERGROUPS;
	    RetValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadPosition : STRUCT
	    AxisNo : DINT;
	    Mode : DINT;
	    Position : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadPosOffset : STRUCT
	    PosOffset : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadProfileActValues : STRUCT
	    Mode : _LMCPROF_ACTUALVALUES;
	    ActualValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadProfileError : STRUCT
	    ErrorInfo : _LMCPROFERRORDEF;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadProfileParameter : STRUCT
	    ParNo : _LMCPROFPARAMETER;
	    RetValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadRestartInfo : STRUCT
	    sRestart : LREAL;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _logParReadRestartPos : STRUCT
	    Positions : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParReadRobotParameter : STRUCT
	    ParNo : _LMCRobotBase::_PARAMETER;
	    Mode : DINT;
	    RetValue : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParRobotIsOn : STRUCT
	    IsOn : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParRobotOn : STRUCT
	    Mode : _LMCRobotBase::_ROBOT_ON_MODE;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetAxisParameter : STRUCT
	    AxisNo : DINT;
	    ParNo : _LMCPROFPARAMETERAXIS;
	    Value : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetBasicParameter : STRUCT
	    VMax : DINT;
	    AMax : DINT;
	    Tjerk : DINT;
	    TangError : DINT;
	    PosOffset : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetDynSWEndPos : STRUCT
	    AxNo : DINT;
	    pSWEndPos : ^DINT;
	    Mode : _LMC_DYN_SWLIMITS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetGroupParameter : STRUCT
	    GrpNo : DINT;
	    ParNo : _LMCPROFPARAMETERGROUPS;
	    Value : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetPosOffset : STRUCT
	    PosOffset : _LMCPROF_POS;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetProfileParameter : STRUCT
	    ParNo : _LMCPROFPARAMETER;
	    Value : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetProfilePositions : STRUCT
	    Mode : _LMCPROF_SETPOS_MODE;
	    pApproxPos : ^_LMCPROF_POS;
	    pCallbackData : pVoid;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetRestartPointFileOffset : STRUCT
	    PathOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetRobotParameter : STRUCT
	    ParNo : _LMCRobotBase::_PARAMETER;
	    Mode : DINT;
	    Value : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParSetTimeBase : STRUCT
	    udTimeBase : UDINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  _LogParStopMove : STRUCT
	    Mode : DINT;
	    Decel : DINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
	  _LogParStretchLastMove : STRUCT
	    FactorMul : UDINT;
	    FactorDiv : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
_LMCTool : CLASS_PUBLIC
	TYPE
#pragma pack(push, 1)
	  _TOOL_DATA_ : STRUCT
	    ToolIndex : DINT;
	    OffsetVector : _LMCMath_SO3::_POINT_;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
_SerLib : CLASS_PUBLIC
	TYPE
	  CmdCommand :
	  (
	    StartUserIPR,
	    StopUserIPR,
	    SerCloseIPR,
	    SerSendIPR,
	    RecvCharIPR,
	    SetOnlineIPR,
	    GetRecvStateIPR,
	    GetSendStateIPR,
	    GetErrorIPR,
	    IsInitializedIPR,
	    ClearRecBufferIPR,
	    RtsOnOffIPR,
	    rdRtsIPR,
	    rdCtsIPR,
	    DtrOnOffIPR,
	    rdDtrIPR,
	    rdDcdIPR,
	    rdDsrIPR,
	    rdRiIPR,
	    SetRSModeIPR,
	    GetRSModeIPR,
	    GetInterfaceTypeIPR
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
_TCPIPServer : CLASS_PUBLIC
#include "..\Class\_TCPIPServer\_TCPIPServer.h"
#include "..\Class\_TCPIPServer\SalamanderDelay.h"
	TYPE
	  _FSM_TCPIP_SERVER :
	  (
	    _STATE_NONE,
	    _STATE_INIT_SERVER,
	    _STATE_NO_USER_INTERFACE_CONNECTED,
	    _STATE_IDLE,
	    _STATE_MAIN_SOCK,
	    _STATE_LISTEN,
	    _STATE_ACCEPT,
	    _STATE_CONNECT,
	    _STATE_RECV,
	    _STATE_SHUTDOWN,
	    _STATE_CLOSE_MAIN_SOCK,
	    _STATE_CLOSE_SOCK,
	    _STATE_ERROR,
	    _STATE_ERROR_ALLOCATING_MEMORY,
	    _STATE_ERROR_CREATING_MUTEX,
	    _STATE_ERROR_CREATING_TASK,
	    _STATE_SEND,
	    _STATE_MAIN_SOCK_OPT,
	    _STATE_DEL_CONNECTION,
	    _STATE_CONN_SOCK_OPT
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
_TCPIPServerInterface : CLASS_PUBLIC
	TYPE
	  _STATE_TCPIP_INTF :
	  (
	    _STATE_ERROR_REGISTRATION,
	    _STATE_RUNNING,
	    _STATE_ERROR_POINTER,
	    _STATE_ERROR_ALREADY_INSTALLED
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
Controller : CLASS_PUBLIC
	TYPE
	  _LMCCONTROLLER_SETPARAMETER :
	  (
	    _LMCCONTROLLER_PAR_SET_CYCLIC_DRIVE_ENABLED_CHECK,
	    _LMCCONTROLLER_PAR_SET_QUICKSTOP_ERRORREACTION
	  )$UDINT;
	  t_e_LMCCONTROLLER_SAFETY_PARAM :
	  (
	    _LMCCONTROLLER_SAFETY_GETVERIFYSTATE,
	    _LMCCONTROLLER_SAFETY_GETREFERENCESTATE,
	    _LMCCONTROLLER_SAFETY_GETSAFETYRUNSTATE,
	    _LMCCONTROLLER_SAFETY_GETSBTSTATE,
	    _LMCCONTROLLER_SAFETY_GETSBTTESTTIME,
	    _LMCCONTROLLER_SAFETY_GETSBTMINTORQUE,
	    _LMCCONTROLLER_SAFETY_GETSBTTESTINTERVAL,
	    _LMCCONTROLLER_SAFETY_GETSAFETYERROR,
	    _LMCCONTROLLER_SAFETY_GETSAFETYFUNCERROR,
	    _LMCCONTROLLER_SAFETY_GETISSS2CONFIGURED,
	    _LMCCONTROLLER_SAFETY_READAXISSTATE:=101,
	    _LMCCONTROLLER_SAFETY_GETSAFECNTRLSTATEWORD,
	    _LMCCONTROLLER_SAFETY_DOSAFETYAXERRORQUIT:=201,
	    _LMCCONTROLLER_SAFETY_SETVERIFYAXIS,
	    _LMCCONTROLLER_SAFETY_SETREFERENCEAXIS,
	    _LMCCONTROLLER_SAFETY_SETACKZEROPOSITION,
	    _LMCCONTROLLER_SAFETY_SETSBTSTATE,
	    _LMCCONTROLLER_SAFETY_SBTACTIVE,
	    _LMCCONTROLLER_SAFETY_CHANGESERVICEMODE,
	    _LMCCONTROLLER_SAFETY_LOGINAXIS:=301
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
ECAT_Master_Base : CLASS_PUBLIC
#include "..\Class\ECAT_Master_Base\ECAT_Master_Base.h"
#include "..\Source\BusInterface.h"
#include "..\Source\interfaces\lsl_st_hardwaretree.h"
#include "..\Class\HwControl\HwControl.h"
#include "..\Source\interfaces\lsl_st_ecatm.h"
#include "..\Source\interfaces\lsl_st_systrace.h"
	TYPE
#pragma pack(push, 1)
	  t_s_EtherCATFrameTimes : STRUCT
	    udEtherCATFrameTime : UDINT;
	    udEtherCATFrameTimeMin : UDINT;
	    udEtherCATFrameTimeMax : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
MerkerEx : CLASS_PUBLIC
#include <.\lsl_st_mt.h>
	TYPE
	  Cmdm_udLength :
	  (
	    GET_DATA_PTR,
	    EXCHANGE_DATA_PTR,
	    SAVE_DATA_TO_RAMEXFILE
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
SafetyCDIAS_Base : CLASS_PUBLIC
#include "..\Class\SafetyCDIAS_Base\SafetyCDIAS_Base.h"
#include "..\Source\interfaces\lsl_st_safety.h"
#include "..\Class\SafetyManager\SafetyManager.h"
	TYPE
	  FrameTypeType : BSINT
	  [
	    1 Cfg,
	    2 ToP,
	    3 Standard,
	    4 PDO,
	    5 TDO,
	    6 Reserved1,
	    7 Reserved2,
	    8 Response,
	  ];
#pragma pack(push, 1)
	  SDOStdHeader : STRUCT
	    CRC : UDINT;
	    Cmd : USINT;
	    Typ : FrameTypeType;
	    SeqNr : USINT;
	    Len : USINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  SDOHeader : STRUCT
	    StdHeader : SDOStdHeader;
	    SrcAdr : HDINT;
	    DstAdr : HDINT;
	    SessId : UDINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
SafetyUDP : CLASS_PUBLIC
	TYPE
	  _FSM_UDP_ERROR :
	  (
	    _NO_ERROR_UDP_ERROR:=0,
	    _INIT_TCP_USER_UDP_ERROR:=4294967295,
	    _NO_IP_ADDRESS_UDP_ERROR:=4294967294,
	    _NO_MEMORY_SOCKET_UDP_ERROR:=4294967293,
	    _NO_MEMORY_SENDBUFFER_UDP_ERROR:=4294967292,
	    _INVALID_HANDLE_UDP_ERROR:=4294967291,
	    _SHUTDOWN_UDP_ERROR:=4294967290,
	    _CLOSESOCKET_UDP_ERROR:=4294967289,
	    _ALLOCATE_SOCKET_UDP_ERROR:=4294967288,
	    _SET_BIND_UDP_ERROR:=4294967287,
	    _RECV_UDP_ERROR:=4294967286,
	    _SEND_UDP_ERROR:=4294967285,
	    _NO_LOCAL_IP_UDP_ERROR:=4294967284,
	    _NO_DESTINATION_IP_UDP_ERROR:=4294967283,
	    _INVALID_UDP_PORT_UDP_ERROR,
	    _INVALID_INTERFACE_NUMBER_UDP_ERROR,
	    _NO_MEMORY_RECEIVE_BUFFER_UDP_ERROR,
	    _NO_MEMORY_CONNECTION_BUFFER_UDP_ERROR
	  )$DINT;
	  _FSM_UDP_USER :
	  (
	    _STATE_INIT_UDP,
	    _STATE_IDLE_UDP,
	    _STATE_SOCK_UDP,
	    _STATE_CONNECT_UDP,
	    _STATE_ONLY_SEND_UDP,
	    _STATE_RECV_UDP,
	    _STATE_SEND_UDP,
	    _STATE_SHUTDOWN_UDP,
	    _STATE_CLOSE_SOCK_UDP,
	    _STATE_ERROR_UDP
	  )$UDINT;
	  _INITSTEPS :
	  (
	    _NO_OPERATION,
	    _ADD_SOCKET,
	    _CHECK_IF_SOCKET_OPEN,
	    _BIND_SOCKET,
	    _CLOSE_CON
	  )$UDINT;
	END_TYPE
END_CLASS;
#pragma define (restore)
#pragma InclDefBlk SdiasBase
SdiasBase : CLASS_PUBLIC
#include "..\Class\SdiasManager\SdiasManager.h"
#include "..\Class\SdiasBase\SdiasBase.h"
#include "..\Class\HwControl\HwControl.h"
#include "..\Source\interfaces\lsl_st_hardwaretree.h"
#include "..\Source\interfaces\lsl_st_mt.h"
	TYPE
	  t_b_SdiasFWState : BINT
	  [
	    1 VoltageNotOk,
	    2 NoSync,
	    3 FlashDataCRCError,
	    4 RAMDataCRCError,
	    5 FlashUnsafe,
	    6 BusTimeNotSupported,
	    7 ToggleBit,
	  ];
#pragma pack(push, 1)
	  t_s_SdiasFWStateStandard : STRUCT
	    ErrorBits : t_b_SdiasFWState;
	    Reserved : UINT;
	  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
	  t_s_SPI_AccessControl : STRUCT
	    udAccessHandle : UDINT;
	    usAccessLength : USINT;
	    usAccessOffset : USINT;
	    pControlByte : t_SDIAS_pControlByte;
	    pStateByte : t_SDIAS_pStateByte;
	  END_STRUCT;
#pragma pack(pop)
	  t_SPI_PDO_DataWrite : ARRAY [0..SDIAS_MAX_PDO_SIZE-1] OF USINT;
	  t_SPI_PDO_DataRead : ARRAY [0..SDIAS_MAX_PDO_SIZE-1] OF USINT;
	  t_e_SPIWriteSSW :
	  (
	    _SPIWrite_Idle,
	    _AllocateMemory,
	    _SetRequest,
	    _ReadGrant,
	    _ReadSectorData_SetPageAddress,
	    _ReadSectorData_Wait4SetPageAddress,
	    _ReadSectorData_SetReadPageCommand,
	    _ReadSectorData_Wait4SetReadPageCommand,
	    _ReadSectorData_ReadReceiveBufferPart1,
	    _ReadSectorData_ReadReceiveBufferPart2,
	    _EraseSector_SetPageAddress,
	    _EraseSector_Wait4SetPageAddress,
	    _EraseSector_SetEraseSectorCommand,
	    _EraseSector_Wait4SetEraseSectorCommand,
	    _WriteSectorData_SetPageAddress,
	    _WriteSectorData_Wait4SetPageAddress,
	    _WriteSectorData_WriteTransmitBufferPart1,
	    _WriteSectorData_WriteTransmitBufferPart2,
	    _WriteSectorData_SetWritePageCommand,
	    _WriteSectorData_Wait4SetWritePageCommand,
	    _VerifySectorData_SetPageAddress,
	    _VerifySectorData_Wait4SetPageAddress,
	    _VerifySectorData_SetReadPageCommand,
	    _VerifySectorData_Wait4SetReadPageCommand,
	    _VerifySectorData_ReadReceiveBufferPart1,
	    _VerifySectorData_ReadReceiveBufferPart2,
	    _VerifySectorData_CompareData,
	    _ClearRequest,
	    _DisableDataObjects,
	    _FreeMemory,
	    _FinishSPIWrite
	  )$UDINT;
	  usWriteModes : USINT;
#pragma pack(push, 1)
	  t_s_SPIWriteVars : STRUCT
	    sWriteAccess : t_s_SPI_AccessControl;
	    pWriteData : ^t_SPI_PDO_DataWrite;
	    sReadAccess : t_s_SPI_AccessControl;
	    pReadData : ^t_SPI_PDO_DataRead;
	    sReadStateAccess : t_s_SPI_AccessControl;
	    pReadStateData : ^USINT;
	    pSectorMemoryRead : ^USINT;
	    pSectorMemoryWrite : ^USINT;
	    pSectorMemoryVerify : ^USINT;
	    pUserWriteData : ^USINT;
	    udUserWriteLength : UDINT;
	    usUserSectorNumber : USINT;
	    usUserPageNumber : USINT;
	    usUserPageOffset : USINT;
	    eSPIWriteSSW : t_e_SPIWriteSSW;
	    eSPIWriteSSWError : t_e_SPIWriteSSW;
	    uiCurrentPage : UINT;
	    udCurrentSectorMemoryOffset : UDINT;
	    usRetryCnt : USINT;
	    bsFinished : BSINT
	    [
	      1 Finished,
	      2 Error,
	      3 Bit3,
	      4 Bit4,
	      5 Bit5,
	      6 Bit6,
	      7 Bit7,
	      8 Bit8,
	    ];
	    usCycleWaitCnt : USINT;
	    udTimeout : UDINT;
	    NotReadyCnt : DINT;
	    usFinishedWriteLog : USINT;
	    usWriteMode : usWriteModes;
	    udMemoryToAllocate : UDINT;
	    uiLastPage : UINT;
	    udUserDataOffset : DINT;
	  END_STRUCT;
#pragma pack(pop)
	END_TYPE
END_CLASS;
#pragma define (restore)
VirtualBaseInit : CLASS_PUBLIC
	TYPE
	  CmdData :
	  (
	    GET_ADD_INFO,
	    READ_DATA,
	    WRITE_DATA,
	    READ_DATA_OFF,
	    WRITE_DATA_OFF
	  )$UINT;
	END_TYPE
END_CLASS;
#pragma define (restore)

#RE_IN_DE
