//This file was generated by the LASAL2 CodeGenerator  --
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
  SvrCh__Config__PTofCls__LMCPublisher : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPublisher::_Config_;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh__Config__PTofCls__LMCPublisher : STRUCT
    pCh : ^SvrCh__Config__PTofCls__LMCPublisher;
    dData : _LMCPublisher::_Config_;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_BDINT : STRUCT
    pMeth : ^CHMETH;
    dData : BDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_BDINT : STRUCT
    pCh : ^SvrCh_BDINT;
    dData : BDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_DINT : STRUCT
    pMeth : ^CHMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_DINT : STRUCT
    pCh : ^SvrCh_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrCh_UDINT : STRUCT
    pMeth : ^CHMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltCh_UDINT : STRUCT
    pCh : ^SvrCh_UDINT;
    dData : UDINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  SvrChCmd__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CMDMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__AxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_AxisBase;
  END_STRUCT;
  SvrChCmd_DINT : STRUCT
    pMeth : ^CMDMETH;
    dData : DINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__CheckSum : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_CheckSum;
  END_STRUCT;
  CltChCmd__Linker : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_Linker;
  END_STRUCT;
  CltChCmd__LMCABSEncoder : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCABSEncoder;
  END_STRUCT;
  CltChCmd__LMCAxis : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxis;
  END_STRUCT;
  CltChCmd__LMCAxisBase : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCAxisBase;
  END_STRUCT;
  CltChCmd__LMCAxisRef : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisRef;
  END_STRUCT;
  CltChCmd__LMCAxisVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVis;
  END_STRUCT;
  CltChCmd__LMCAxisVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisInt;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogHandle : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogHandle;
  END_STRUCT;
  CltChCmd__LMCAxisVisLogViewer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisLogViewer;
  END_STRUCT;
  CltChCmd__LMCAxisVisPara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVisPara;
  END_STRUCT;
  CltChCmd__LMCAxisVOVMonitoring : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCAxisVOVMonitoring;
  END_STRUCT;
  CltChCmd__LMCBaseCoord : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCBaseCoord;
  END_STRUCT;
  CltChCmd__LMCBeltAxis : STRUCT
    pCh : ^SvrChCmd__LMCAXIS_OPMODE;
    dData : _LMCAXIS_OPMODE;
    pCmd : ^_LMCBeltAxis;
  END_STRUCT;
  SvrChCmd_ProfileCommandStatus : STRUCT
    pMeth : ^CMDMETH;
    dData : ProfileCommandStatus;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__LMCCalcModelBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCCalcModelBase;
  END_STRUCT;
  CltChCmd__LMCCalcModelController : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCCalcModelController;
  END_STRUCT;
  CltChCmd__LMCMath_SO3 : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCMath_SO3;
  END_STRUCT;
  CltChCmd__LMCMathFunctions : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCMathFunctions;
  END_STRUCT;
  CltChCmd__LMCProfile : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCProfile;
  END_STRUCT;
  CltChCmd__LMCProfileBase : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^_LMCProfileBase;
  END_STRUCT;
  CltChCmd__LMCProfileBuffer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileBuffer;
  END_STRUCT;
  CltChCmd__LMCProfileLog : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileLog;
  END_STRUCT;
  CltChCmd__LMCProfileVis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVis;
  END_STRUCT;
  CltChCmd__LMCProfileVisAxis : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisAxis;
  END_STRUCT;
  CltChCmd__LMCProfileVisInt : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisInt;
  END_STRUCT;
  CltChCmd__LMCProfileVisMovePara : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCProfileVisMovePara;
  END_STRUCT;
  CltChCmd__LMCPublisher : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCPublisher;
  END_STRUCT;
  CltChCmd__LMCRefBase : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCRefBase;
  END_STRUCT;
  CltChCmd__LMCRobotLog : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCRobotLog;
  END_STRUCT;
  CltChCmd__LMCSafety : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCSafety;
  END_STRUCT;
  CltChCmd__LMCSplineBuffer : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCSplineBuffer;
  END_STRUCT;
  SvrChCmd_UDINT : STRUCT
    pMeth : ^CMDMETH;
    dData : UDINT;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__LMCTableBuffer : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^_LMCTableBuffer;
  END_STRUCT;
  CltChCmd__LMCTool : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_LMCTool;
  END_STRUCT;
  CltChCmd__MultiTask : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_MultiTask;
  END_STRUCT;
  CltChCmd__SigTCPDataManager : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_SigTCPDataManager;
  END_STRUCT;
  CltChCmd__StdLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_StdLib;
  END_STRUCT;
  CltChCmd__TaskObjectControl : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^_TaskObjectControl;
  END_STRUCT;
  SvrChCmd__FSM_UDP_USER_PTofCls__UDPTransceiver : STRUCT
    pMeth : ^CMDMETH;
    dData : _UDPTransceiver::_FSM_UDP_USER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  CltChCmd__UDPTransceiver : STRUCT
    pCh : ^SvrChCmd__FSM_UDP_USER_PTofCls__UDPTransceiver;
    dData : _UDPTransceiver::_FSM_UDP_USER;
    pCmd : ^_UDPTransceiver;
  END_STRUCT;
  CltChCmd_Controller : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Controller;
  END_STRUCT;
  CltChCmd_CriticalSection : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^CriticalSection;
  END_STRUCT;
  CltChCmd_DataManager : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^DataManager;
  END_STRUCT;
  CltChCmd_DataManagerFIFO : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^DataManagerFIFO;
  END_STRUCT;
  CltChCmd_DataManagerPriority : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^DataManagerPriority;
  END_STRUCT;
  CltChCmd_DINT : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_GetTaskHandle : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^GetTaskHandle;
  END_STRUCT;
  CltChCmd_Merker : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^Merker;
  END_STRUCT;
  CltChCmd_MerkerEx : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^MerkerEx;
  END_STRUCT;
  CltChCmd_ProfileCommandStatus : STRUCT
    pCh : ^SvrChCmd_ProfileCommandStatus;
    dData : ProfileCommandStatus;
    pCmd : ^SVRCHCMD;
  END_STRUCT;
  CltChCmd_RamRingBuffer : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^RamRingBuffer;
  END_STRUCT;
  CltChCmd_SigCLib : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^SigCLib;
  END_STRUCT;
  CltChCmd_String : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^String;
  END_STRUCT;
  CltChCmd_StringInternal : STRUCT
    pCh : ^SvrChCmd_UDINT;
    dData : UDINT;
    pCmd : ^StringInternal;
  END_STRUCT;
  CltChCmd_TCPCommunication : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TCPCommunication;
  END_STRUCT;
  CltChCmd_TCPCommunicationLogFilter : STRUCT
    pCh : ^SvrChCmd_DINT;
    dData : DINT;
    pCmd : ^TCPCommunicationLogFilter;
  END_STRUCT;
  SvrCh__CommandList_PTofCls__LMCAxisBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAxisBase::_CommandList;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__FSM_UDP_USER_PTofCls__UDPTransceiver : STRUCT
    pMeth : ^CHMETH;
    dData : _UDPTransceiver::_FSM_UDP_USER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_CMDERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_CMDERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_ERROR_CONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_ERROR_CONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVE_RELATIVE_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVE_RELATIVE_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEDIRECTION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEDIRECTION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_MOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_MOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POSMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POSMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_POWER_OFF_MODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_POWER_OFF_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_REFMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_REFMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETPOSITION : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETPOSITION;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_SETSWENDPOS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_SETSWENDPOS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCAXIS_STATUS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAXIS_STATUS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCCONTROLLERTYPE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCCONTROLLERTYPE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROF_OPMODE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROF_OPMODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCIRCLEDEF : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCIRCLEDEF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFCMDTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFCMDTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRORTYPES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRORTYPES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFERRWARNCONFIG : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFERRWARNCONFIG;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFILESTATES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFILESTATES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFMOVEPROFILE : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFMOVEPROFILE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETER : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETER;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERAXIS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERAXIS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFPARAMETERGROUPS : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFPARAMETERGROUPS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__LMCPROFTRANSMODES : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCPROFTRANSMODES;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__POSFLAGS : STRUCT
    pMeth : ^CHMETH;
    dData : _POSFLAGS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__ROBOT_MODE_PTofCls__LMCRobotBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCRobotBase::_ROBOT_MODE;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__ROBOT_STATUS_PTofCls__LMCRobotBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCRobotBase::_ROBOT_STATUS;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__STATE_UDP_INTF_PTofCls__UDPTransceiverInterface : STRUCT
    pMeth : ^CHMETH;
    dData : _UDPTransceiverInterface::_STATE_UDP_INTF;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh__UDP_ERROR_PTofCls__UDPTransceiver : STRUCT
    pMeth : ^CHMETH;
    dData : _UDPTransceiver::_UDP_ERROR;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication : STRUCT
    pMeth : ^CHMETH;
    dData : TCPCommunication::t_e_ConnectionType;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_e_TransmissionState_PTofCls_UDPTransmission : STRUCT
    pMeth : ^CHMETH;
    dData : UDPTransmission::t_e_TransmissionState;
    pDsc : ^SVRDSC;
  END_STRUCT;
  SvrCh_t_s_LMCAxis_SafetyState_PTofCls__LMCAxisBase : STRUCT
    pMeth : ^CHMETH;
    dData : _LMCAxisBase::t_s_LMCAxis_SafetyState;
    pDsc : ^SVRDSC;
  END_STRUCT;
END_TYPE
